### ISSUE TITLE
Req 5: The API shall publish records as GeoJSON

### ISSUE THREAD

**Issue by AlwynSmit** [healthsites/healthsites#1002]
The API shall publish records as GeoJSON with each facility being provided as a point geometry.

child of #997

**Comment by timlinux** [comment]
Note that we opted for date range parameters and pagination. With pagination using geojson doesnt make so much sense. Instead we fixed the country shp file extracts.

**Comment by meomancer** [comment]
https://healthsites.io/api/docs/
some of API has geojson parameter that can return as geojson
