### ISSUE TITLE
Kartoza Epic 2: User Story 2: Publish new health sites records via HS.io API to OSM

### ISSUE THREAD

**Issue by AlwynSmit** [healthsites/healthsites#1006]
# Expectation
When a new record is inserted via the HS.io API, I want to see that record appear in osm.org after a short interval.

# Acceptance criteria
Given that the HS.io  API is verified through unit testing to meet the specified requirements, when a user inserts  a new record in HS.IO via the API then this record shall appear in OSM associated a new node id and be retrievable  via overpass.

child of #996

requires #1024

**Comment by timlinux** [comment]
Input data shall be in the same format as defined in #1028

**Comment by timlinux** [comment]
@meomancer Can you do this ticket in two parts:

1) Create a stub interface that doesnt actually write anything to OSM so that eHealth team can start to build against it.
2) Wire in the actual logic to write to OSM

**Comment by meomancer** [comment]
Currently it will be saved into OSM
But it needs time to show in HS because docker osm cache need to pull it
To handle this, when the data is not pulled yet, when in map, it will tell the data is still in pending and redirect into osm
