### ISSUE TITLE
Kartoza Epic 3: Review and migrate any data that is in HS.io and not in OSM into OSM

### ISSUE THREAD

**Issue by AlwynSmit** [healthsites/healthsites#1007]
Review and migrate any data that is in HS.io and not in OSM into OSM

**Comment by meomancer** [comment]
Will be done after : https://github.com/healthsites/healthsites/issues/1106 done

**Comment by meomancer** [comment]
updated with this ticket : https://github.com/healthsites/healthsites/issues/1155

**Comment by meomancer** [comment]
the command already provided
