### ISSUE TITLE
Kartoza Epic 5: User Story 1:  Local mirror of all OSM healthsites

### ISSUE THREAD

**Issue by AlwynSmit** [healthsites/healthsites#1012]
# Expectation
The system shall be designed such that we have a local mirror of all OSM healthsites stored in an always-synchronised local postgresql database.
 
# Acceptance criteria

- Given that the HS.io database is interrogated, when a system administrator queries the database, then all healthsites records in OSM shall be present in the database.

child of #1011

**Comment by meomancer** [comment]
I think this is fixed with : https://github.com/healthsites/healthsites/pull/1079
