### ISSUE TITLE
Kartoza Epic 6: User Story 1: Local HS.io non-OSM data

### ISSUE THREAD

**Issue by AlwynSmit** [healthsites/healthsites#1014]
# Expectation
The system shall be designed such that we have a local database containing one companion record containing only HS.io non-OSM data per OSM healthsites record.
 
# Acceptance criteria

Given that the HS.io database is interrogated, when a system administrator queries the database, then all there shall be one record per OSM healthsites record linked by the node id.

child of #1013

**Comment by meomancer** [comment]
Will be done after : https://github.com/healthsites/healthsites/issues/1106 done

**Comment by meomancer** [comment]
fixed by #1107
