### ISSUE TITLE
Kartoza Epic 1: User Story 5: Use only OSM Auth

### ISSUE THREAD

**Issue by timlinux** [healthsites/healthsites#1026]
Remove Twitter and Facebook oauth support and ensure any logged in user has done so via their OSM credentials.

child of #992

**Comment by markherringer** [comment]
@timlinux we need to present a message to existing users (twitter, facebook) as they login. The message will explain that they need to establish an OSM account to be able to edit Healthsites

**Comment by markherringer** [comment]
@timlinux I'm getting the following error..

Server Error (500)

Which preferences need to be set?

**Comment by meomancer** [comment]
@markherringer where did you try it?
still on staging : https://staging.healthsites.io/
i'm able to login with osm

**Comment by meomancer** [comment]
Currently we are going to show FB and Twitter too, with some restriction
please see workable ticket : https://github.com/healthsites/healthsites/issues/1126
