### ISSUE TITLE
Kartoza Epic 1: User Story 6: Create OSM API Abstraction layer

### ISSUE THREAD

**Issue by timlinux** [healthsites/healthsites#1027]
This is a utility library that will abstract all the CRUD operations to OSM from HS.IO

child of #992

**Comment by lucernae** [comment]
@timlinux can you elaborate this? Does in this case OSM is the upstream OSM or just local docker-osm  instance?

**Comment by timlinux** [comment]
In this case we wantt o write directly to OSM, not the docker-osm mirror. When changes are made in OSM upstream, they will propogate to the docker-osm mirror.

**Comment by meomancer** [comment]
Fixed by : #1099
