### ISSUE TITLE
Kartoza Epic 2: User Story 3: Define interchange format for publishing health sites via API

### ISSUE THREAD

**Issue by timlinux** [healthsites/healthsites#1028]
When we publish records via our API there should be a well defined and documented format for these data.

Data will be published in GeoJSON.

To complete this ticket we should have a detailed specification document (could be generated by DRF) describing the format of published data.

child of #996

**Comment by meomancer** [comment]
Using DRF is quite hard, because some of fields can be generated by latest DRF that needs django 2
So we are using manual json schema, but we need it to be generated based on validator for osm

this is the ticket
https://github.com/healthsites/healthsites/issues/1128

**Comment by meomancer** [comment]
Already done using schema https://healthsites.io/api/schema/
