### ISSUE TITLE
Kartoza Epic 5: User Story 2:  Setup docker osm

### ISSUE THREAD

**Issue by meomancer** [healthsites/healthsites#1030]
Add docker OSM in our orchestration

child of #1012

**Comment by markherringer** [comment]
@timlinux @meomancer https://aws.amazon.com/blogs/big-data/querying-openstreetmap-with-amazon-athena/ looks like a potential alternative to Docker OSM.

**Comment by timlinux** [comment]
See also https://github.com/healthsites/healthsites/issues/856 for comments on what features we should be fetching into HS.io

**Comment by timlinux** [comment]
For clarification we need docker-osm to maintain a synchronised copy of OSM healthsites data within our own infrastructure

**Comment by meomancer** [comment]
it is already done
