### ISSUE TITLE
Problem with Twitter login

### ISSUE THREAD

**Issue by AlwynSmit** [healthsites/healthsites#1044]
The twitter authentication process is currently not working. 
https://healthsites.io/signin/

**Comment by nixilla** [comment]
possibly related to #215

**Comment by nixilla** [comment]
`ERROR 2018-09-13 12:20:13,805 base 9467 140280636352256 [u'HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/oauth/request_token', u'  File "django/core/handlers/base.py", line 132, in get_response', u'  File "django/views/decorators/cache.py", line 57, in _wrapped_view_func', u'  File "social/apps/django_app/utils.py", line 51, in wrapper', u'  File "social/apps/django_app/views.py", line 19, in auth', u'  File "social/actions.py", line 28, in do_auth', u'  File "social/backends/base.py", line 36, in start', u'  File "social/backends/oauth.py", line 165, in auth_url', u'  File "social/backends/oauth.py", line 221, in set_unauthorized_token', u'  File "social/backends/oauth.py", line 245, in unauthorized_token', u'  File "social/backends/base.py", line 225, in request', u'  File "requests/models.py", line 935, in raise_for_status']`

**Comment by nixilla** [comment]
possibly related to https://github.com/python-social-auth/social-app-django/issues/164 where solution is to [upgrade 2 dependencies](https://github.com/python-social-auth/social-app-django/issues/164#issuecomment-399730181)

**Comment by meomancer** [comment]
we are just using osm credential because we need that credential to push the data to osm

**Comment by markherringer** [comment]
@meomancer user will login with twitter, facebook and be presented with a message explaining the requirement to have an OSM user account to write updates. 

We need to establish continuity with the existing users and their data.

This will ensure that user swill still be able to share health facility data using twitter ect.
