### ISSUE TITLE
We need to upgrade to django 1.11

### ISSUE THREAD

**Issue by timlinux** [healthsites/healthsites#1058]
See https://github.com/healthsites/healthsites/issues/1018 - we need to use a more current version of django than 1.8 which we currently have so that we can generate API schema for write operations in django rest framework. Please cap your effort to 4 hours and if you encounter problems we can review.

**Comment by timlinux** [comment]
@meomancer can you confirm this is done?

**Comment by meomancer** [comment]
hi @timlinux 
currently the api docs is working fine (and the schema is already working fine too)
other ticket that is for upgrading : https://github.com/healthsites/healthsites/issues/1440
