### ISSUE TITLE
Support POST operations to API

### ISSUE THREAD

**Issue by timlinux** [healthsites/healthsites#1069]
Currently we have only PUT method for writing records to HS.io via the API, and this requires a UUID which the client will likely not have since they are doing a record insert.

Please implement support for POSTing new records.

CC @shawnsarwar 

child of #996

**Comment by meomancer** [comment]
Already added POST method to create facility
in here
http://116.203.102.205/api/v2/facilities?api-key=f591a75c55c3111aa52cc0c90a2d61e64d094318
