### ISSUE TITLE
We need the OSM user id for each feature in the osm-cache

### ISSUE THREAD

**Issue by timlinux** [healthsites/healthsites#1076]
Currently the mapping file for the docker-osm / osm-cache returns back data like this:

<img width="1316" alt="image" src="https://user-images.githubusercontent.com/178003/52926388-f86efe00-334e-11e9-9d5d-48b09a88170c.png">

Can you check if we are able to include the OSM user id for each node, way, relation.

We need that so that we can support things like the latest updates page:

http://116.203.102.205/profile/timlinux406a5595659b4a7b/

That user name must be matched back to our django user accounts via their social auth so that we can see data created by that user

**Comment by timlinux** [comment]
child of #1011

**Comment by meomancer** [comment]
i think docker osm doesn't provide how to get the uploader (already checked the documentation)
maybe we could use OSMCha for this?

**Comment by timlinux** [comment]
Yes and we need to get the last edit time too. Ideally implementation should be done inside of osm-docker container so everything is encapsulated in one place.

**Comment by meomancer** [comment]
Already fixed by extend docker osm with docker osm enrich
PR : https://github.com/healthsites/healthsites/pull/1079
