### ISSUE TITLE
We need to cache the front page stats

### ISSUE THREAD

**Issue by timlinux** [healthsites/healthsites#1078]
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/178003/53296562-21453680-381a-11e9-977f-a0dd565d6399.png">

Currently it takes a long time to load up the front page

http://116.203.102.205

Can we cache those stats of something to make it load up faster?

**Comment by meomancer** [comment]
It is bug, because the statistic for world on staging just taking like 2-3 secs
Already fixed by https://github.com/healthsites/healthsites/pull/1107
