### ISSUE TITLE
facilities in OSM not apprearing in staging

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#1083]
@timlinux here are the links to review

https://www.openstreetmap.org/node/6141086502

https://staging.healthsites.io/map?place=Kalemi%20drc

![drc-missing-hs](https://user-images.githubusercontent.com/38838/54277117-31397600-458f-11e9-8c97-a32f6884cad6.png)

**Comment by timlinux** [comment]
@meomancer just verified indeed we are missing clinics here:

<img width="332" alt="image" src="https://user-images.githubusercontent.com/178003/54513720-27798f00-4950-11e9-91f6-aad05bcf052e.png">


Can you look into this and see if your mapping file is missing something. Maye also check in the HS.io db and see if we have the data but are not rendering it for some reason?

**Comment by meomancer** [comment]
hi @markherringer 
it is not implemented yet, and also, it should search using "healthsite" option, not using "Place" options

**Comment by markherringer** [comment]
@meomancer is the bug fixed? Have the missing locations been imported?

**Comment by meomancer** [comment]
It is not implemented yet
The PR is here : https://github.com/healthsites/healthsites/pull/1130
need to merge this and deploy it into staging

**Comment by meomancer** [comment]
Staging has been updated:
http://staging.healthsites.io//map#!/locality/node/6141086502

**Comment by timlinux** [comment]
Thanks @meomancer
