### ISSUE TITLE
Data fetching api needs to allow filtering by country too

### ISSUE THREAD

**Issue by timlinux** [healthsites/healthsites#1084]
from @shawnsarwar : 

> @Tim I have a question pertaining to the HDX integration as well that can go into the doc. I know we've talked about making things filterable temporally by something like `last_modified >= $some_datetime` . Is there also an existing filter for `country == $some_country`? Since the HDX datasets are all broken out that way, I think it's going to be required if not already implemented. (edited)

**Comment by meomancer** [comment]
hi @timlinux @shawnsarwar 
is it for api v1?
because api v2 already able to filter by country

**Comment by timlinux** [comment]
Ah cool sorry I missed that
