### ISSUE TITLE
save healthsite update to db

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#1114]
Open a facility, edit an attribute, save

https://staging.healthsites.io/map#!/locality/286c4cb6586243efb9ebf42a3544c648

![submit](https://user-images.githubusercontent.com/38838/57029396-ead4cf00-6c41-11e9-803d-3b4630aa1340.jpeg)

..but the form does not submit
I understand that we are writing to the current postgres db

**Comment by meomancer** [comment]
This is covered by https://github.com/healthsites/healthsites/pull/1209
saving into database is not necessary, because we are save directly into osm
