### ISSUE TITLE
Update Create/Edit sidebar

### ISSUE THREAD

**Issue by meomancer** [healthsites/healthsites#1127]
# Problem
Currently our edit/update is not updated using new API and new format. 

# Solution
- Please update edit/create using require js and backbone
- Please use new API with new format data
- Add "comment" change because osm recommend this

**Comment by markherringer** [comment]
@meomancer thanks for making a start with the health facility form 'tips'

'..please define notes hospitalisation and outpatient consultation'

https://staging.healthsites.io/map#!/locality/way/319377840

Where are you getting this copy from?
Could you share a document we can use to define the correct copy?

**Comment by meomancer** [comment]
For is already using new approach
the docuemnt in here @markherringer 
https://docs.google.com/spreadsheets/d/1P11VJPocQ5EkmoFaTMItg3z6Rdon2A1M2kIqqjIc-Cw/edit#gid=1195977473
