### ISSUE TITLE
Front page country summary needs to be updated to reflect OSM data

### ISSUE THREAD

**Issue by timlinux** [healthsites/healthsites#1134]
Front page country stats need to be current to the data

<img width="511" alt="image" src="https://user-images.githubusercontent.com/178003/57617578-06f93a00-7579-11e9-9402-e18fa2bfbbe6.png">

And the chart should be broken down by amenity type:

<img width="410" alt="image" src="https://user-images.githubusercontent.com/178003/57617534-ec26c580-7578-11e9-8bdb-67b0c88ec169.png">

<img width="529" alt="image" src="https://user-images.githubusercontent.com/178003/57617499-ddd8a980-7578-11e9-8214-942b3250e9c0.png">

**Comment by meomancer** [comment]
Fixed in staging
