### ISSUE TITLE
Site shows no name when it has one

### ISSUE THREAD

**Issue by timlinux** [healthsites/healthsites#1137]
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/178003/57618098-6441bb00-757a-11e9-80fa-eca9e42ebd45.png">

Look at the tooltip and in the site details - it has a name, but in the side panel it shows no name....

**Comment by meomancer** [comment]
Fixed in staging

**Comment by timlinux** [comment]
Thanks @meomancer
