### ISSUE TITLE
Upgrade command to migrate old data

### ISSUE THREAD

**Issue by meomancer** [healthsites/healthsites#1155]
# Problem
current command is just saving extension data into extension model, no process yet for create/update into osm

# Solution
- Check locality is already in osm cache
- If already there, do the conflict handling
- If no, write new into osm

Checking osm is based on
- check source of locality (already handle by current command)
- check by location and name

depend on #1106

**Comment by ann26** [comment]
The current migrate command to migrate old database only handles the data that has osm id
