### ISSUE TITLE
We need to add eHealth Africa and Kartoza logos and links to the partners section

### ISSUE THREAD

**Issue by timlinux** [healthsites/healthsites#1160]
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/178003/58017290-ba24de80-7af7-11e9-9464-7a22998d21b5.png">

@djmoran64 to provide logo and link for eHealth

**Comment by timlinux** [comment]
@timlinux to get signed MoU and @meomancer please link the MOU's to the kartoza and eHealth logos

**Comment by meomancer** [comment]
hi @timlinux 
could we start working on this ticket?

**Comment by djmoran64** [comment]
![eha_blue_rgb](https://user-images.githubusercontent.com/25639664/61213005-d2694200-a6d1-11e9-8c81-b6fb0441f4e6.png)

Link to: https://www.ehealthafrica.org/

**Comment by markherringer** [comment]
update Geomatica logo

![GEO_LOGO_2019](https://user-images.githubusercontent.com/38838/80483595-a5330b00-8956-11ea-9950-52fd9ab1681e.png)

**Comment by meomancer** [comment]
new ticket for geometica : https://github.com/healthsites/healthsites/issues/1443
