### ISSUE TITLE
Downloaded shapefile has blank OSM id

### ISSUE THREAD

**Issue by timlinux** [healthsites/healthsites#1164]
<img width="889" alt="Screenshot 2019-05-20 at 12 39 29" src="https://user-images.githubusercontent.com/178003/58019000-5224c700-7afc-11e9-8c9d-70a547a25bb7.png">

Can you see why the ID is blank and generally review the other columns in the downloaded shapefile to ensure they are being populated meaningfully?

**Comment by meomancer** [comment]
It is fixed and also fix the column orders
![Selection_148](https://user-images.githubusercontent.com/4530905/58070890-e9ede800-7bc4-11e9-8604-b3e799879110.png)

**Comment by meomancer** [comment]
I'm sorry i closed it @timlinux 
could you check it?
