### ISSUE TITLE
Some points not explodable

### ISSUE THREAD

**Issue by timlinux** [healthsites/healthsites#1165]
https://staging.healthsites.io/map?country=Portugal#!/locality/node/5611886943

![hs](https://user-images.githubusercontent.com/178003/58019218-eabb4700-7afc-11e9-9311-97105e4be99f.gif)

**Comment by meomancer** [comment]
hi @ann26 
please handle this
i think when we are in max zoom, please show all point with "no cluster" on api, but on leaflet, still create cluster but expandable

**Comment by meomancer** [comment]
hi @timlinux 
@ann26 already handle it, could you check it?
