### ISSUE TITLE
Please use the OSM testing server to test OSM write API

### ISSUE THREAD

**Issue by timlinux** [healthsites/healthsites#1167]
From Grant Slater:

> Yes, there are: https://apis.dev.openstreetmap.org/
> They are completely free standing and you need to sign up to them independently. The main one has some limited sample data, but you'd likely need to upload your own test data.

Please can you get a unit testing workflow in place with the key CRUD operations across OSM API that performs the operation against the testing server and then uses the test server API to confirm the operation result.

Regards

Tim

**Comment by meomancer** [comment]
hi @myarjunar 
could you handle this, maybe also with unit test from create/update API
i think we don't have utilities to read/delete, please check this ticket (https://github.com/healthsites/healthsites/issues/1171) to work on read/delete
