### ISSUE TITLE
Div width on mobile

### ISSUE THREAD

**Issue by timlinux** [healthsites/healthsites#1168]
When displaying on mobile we get this little div white stripe on the side:

![Screenshot_20190518-214857](https://user-images.githubusercontent.com/178003/58024637-8e5f2400-7b0a-11e9-8672-2dd734fa370b.png)

**Comment by meomancer** [comment]
hi @timlinux could you check this?
@ann26 already fixed this
![Selection_149](https://user-images.githubusercontent.com/4530905/58077286-689f5100-7bd6-11e9-991b-82d859403d6d.png)
![Selection_150](https://user-images.githubusercontent.com/4530905/58077289-6a691480-7bd6-11e9-8316-2c443b5cca40.png)
