### ISSUE TITLE
Links to user not working

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#1169]
Click on a user name that is not registered in Healthsites. The user is an OSM user only.

![image](https://user-images.githubusercontent.com/38838/58031056-f10eea80-7b1f-11e9-88c6-f747bc0e04c5.png)

Proposed fix.
If user is not registered in healthsites link to OSM profile page.

**Comment by meomancer** [comment]
Fixed, it will just show changests from osm cache

**Comment by meomancer** [comment]
could you check it @markherringer ?
