### ISSUE TITLE
share button

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#1187]
As a user I would like to share healthsite locations and country pages to facebook and twitter using the social media share button 

![image](https://user-images.githubusercontent.com/38838/58226236-11a89180-7d26-11e9-94af-54d3acb50dea.png)

**Comment by meomancer** [comment]
already bring back "twitter share button"
originally we just has twitter share button, the others can be done in here
![Selection_160](https://user-images.githubusercontent.com/4530905/58230528-cc548600-7d5e-11e9-809e-56969ccb74e8.png)

**Comment by meomancer** [comment]
we need more solution
update share button likes the top one

**Comment by markherringer** [comment]
@ann26 what's the plan to give existing users (Twitter, Facebook) access to their accounts and the invitation to establish their OSM accounts?
From there they are able to save their data to OSM.

**Comment by meomancer** [comment]
hi @markherringer 
everyone will be relogin using osm
current code, we just show osm for login, so login will be using osm
and we force all user to logout from backend. so user will be forced to login when they access HS

**Comment by meomancer** [comment]
Done
