### ISSUE TITLE
Version 2 API Permissions framework

### ISSUE THREAD

**Issue by timlinux** [healthsites/healthsites#1193]
@meomancer as we discussed today, can you please implement the API permissions according to this scheme:

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/178003/58313359-463f4a80-7e05-11e9-86cd-1a7d88f855cb.png">

We will also need to add a banner to the site indicating that API v1 will be deprecated at the end of the year and that it will not contain OSM cached data.

**Comment by meomancer** [comment]
Permission has established
When upload data using "osm_user" on payload, uploader need to be the organizer of organisation and the osm_user need to be the trusted user of that organisation

**Comment by markherringer** [comment]
Please add an instructions on how to set up the V2 API service in the form of an error message on V1.

@timlinux is this the best way to try and retain the existing API users?

**Comment by markherringer** [comment]
We need the user to complete the following form fields when registering for the API token
Organisation name
Contact name
Contact email
Site URL
Checkbox acknowledging ODbL license

**Comment by meomancer** [comment]
hi @markherringer 
I created the form for that
could you check it on my PR : https://github.com/healthsites/healthsites/pull/1289
