### ISSUE TITLE
We need to document required functionality for v1

### ISSUE THREAD

**Issue by timlinux** [healthsites/healthsites#12]
The first version should provide the following functionality:
# Map with OSM underlay
- Full screen map with top bar (as per wireframe above) (see #20 )
- Sites should be rendered as geojson using leaflet point clustering (how will this scale to ~1000 of points?) (see #21)
- Clicking on a site should reveal the item info and its contextual info
# Point creation
- Click 'add site to map'
- On clicking 'add site to map', the user should be prompted to log in using oauth if they are not already logged in (see #22)
- Return user to same position on the map with marker cross hairs activated
- User locates the site by dragging the map and toggling the satelite image and map view (need a ticket)
- Clicking the site on the map activates the red marker and the small pop-up window as per http://users.inasafe.org/
- User completes form
- Lat long auto-populated
- Click the 'more..' link in the small form opens the slider window on the right with data loaded
  ![home-add-location-inasafe](https://cloud.githubusercontent.com/assets/38838/4783885/f42d10b0-5d39-11e4-8ffc-6b6baead90cd.png)
- Place the cursor in the next empty field
- Move the map and the site position so that it is horizontal with the first field
- After the site is accepted, it should turn into a blue marker as per image below and the new site modal should be removed

![selection_009](https://cloud.githubusercontent.com/assets/178003/4736431/4ea06aca-59ec-11e4-922b-d905955bc328.png)

![selection_010](https://cloud.githubusercontent.com/assets/178003/4736478/c15b28a2-59ec-11e4-845d-8af7e5b582ac.png)
# About

There should be a simple about box - @markherringer to provide markup

**Comment by markherringer** [comment]
![healthsites io-roadmap1](https://cloud.githubusercontent.com/assets/38838/15142684/14db7d3c-169e-11e6-8078-36c0b9ca8b1b.png)

**Comment by markherringer** [comment]
![healthsites io-roadmap1 1](https://cloud.githubusercontent.com/assets/38838/15143190/61ddc5de-16a0-11e6-82c4-f53a9bc66c90.png)
