### ISSUE TITLE
update national border polygon

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#1214]
As a user I expect the national polygon to conform to the national boundary line.

![image](https://user-images.githubusercontent.com/38838/60506076-57f9f480-9cc5-11e9-97b1-5b3ee546dd40.png)

**Comment by meomancer** [comment]
What we need to do:
1. we need to find updated shapefile : last time we can find it in http://www.naturalearthdata.com/downloads/
2. add this files into "/healthsites/data"
3. run command "python manage.py generate_countries"
4 maybe you could rename the filename and update generate_countries.py command accordingly

**Comment by meomancer** [comment]
hi @markherringer 
https://staging.healthsites.io/map?country=Senegal

we are using maritime boundary, exactly like osm boundary

**Comment by meomancer** [comment]
are you happy @markherringer ?
