### ISSUE TITLE
update URL on selection of pin

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#1237]
As a user I expect the URL to change when I select the pin.

The URL should should include the UUID in the same way as the current live site:
https://healthsites.io/map#!/locality/286c4cb6586243efb9ebf42a3544c648

Currently if you change from one pin to another the URL does not change. You have to select the copy in the pop-up to achieve this. We've decided to remove this copy from the pop.
https://staging.healthsites.io/map#!/locality/way/26989989

**Comment by meomancer** [comment]
url is updatet when pin is selected
but still not using uuid

please try this

**Comment by meomancer** [comment]
This is for update URL that is done
for using uuid, it is handle by another ticket : https://github.com/healthsites/healthsites/issues/1208
