### ISSUE TITLE
opening hours

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#1243]
As a user I want to select easily define the opening hours of a facility.

 
https://docs.google.com/spreadsheets/d/1oauO_HAV0b-b9Cr9iuhOHPjsFh0k57hlkN3ZOIEJynU/edit?usp=sharing

https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification

https://github.com/arteria/django-openinghours

<img width="505" alt="BuoPb" src="https://user-images.githubusercontent.com/38838/61121678-16750080-a4a0-11e9-892d-807c1bfaf64f.png">

https://healthsites.io/map#!/locality/node/6630814286

**Comment by meomancer** [comment]
the form https://github.com/healthsites/healthsites/pull/1296
