### ISSUE TITLE
geolocate me link not working

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#1253]
Placing me in the image below instead of [Saint Louis](https://healthsites.io/map#!/locality/way/202175615?place=Saint%20Louis%20Senegal#!/locality/way/202175615)

![image](https://user-images.githubusercontent.com/38838/61305634-ad142b00-a7da-11e9-9d34-4345f84d62b6.png)

**Comment by meomancer** [comment]
hi @markherringer 
the geolocate me is based on browser location and we can't control that
it seems the location on browser is not updated on your browser
