### ISSUE TITLE
remove the pop-up on location select

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#1272]
Please could we remove the pop-up on the selected location. It obscures the view on the map and other locations.

![image](https://user-images.githubusercontent.com/38838/61630638-bb999100-ac77-11e9-8cc2-b85b39ac503e.png)

https://healthsites.io/map#!/locality/node/2096434514

**Comment by meomancer** [comment]
this has been updated and deployed
please test it

**Comment by meomancer** [comment]
fixed
