### ISSUE TITLE
osm attribute sync

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#1287]
As a Healthsites user I expect to see the healthsites data model replicated in OSM. If OSM has a 'contact:phone' for a facility or 'emergency' status I expect to see it replicated in Healthsites.

https://healthsites.io/map#!/locality/way/23646818

https://www.openstreetmap.org/way/23646818

https://wiki.openstreetmap.org/wiki/Global_Healthsites_Mapping_Project#Complete

**Comment by meomancer** [comment]
hi @markherringer 
you said 'contact:phone' but that osm using just 'contact'. that why we can't replicate it

**Comment by meomancer** [comment]
hi @markherringer 
do you have any news how we resolve this ticket?

**Comment by markherringer** [comment]
It will be useful to know that the attribute has been saved using 'phone' rather than 'contact:phone'
will close this one and write a new one
