### ISSUE TITLE
identify incorrectly tagged facility telephone number

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#1292]
Some health facilities have had their number saved under the 'phone' tag rather than the 'contact:phone' tag.As a result we do not see them in Healthsites.

My understanding is that the 'contact:phone' tag is the preferred tag.

As a user I would like to know that there is a number saved and that it should be saved to the contact:phone tag.

It will be useful to know that the attribute has been saved using 'phone' rather than 'contact:phone'

I will close this one and write a new one

**Comment by pyrog** [comment]
> My understanding is that the `contact:phone` tag is the preferred tag.

According [tag info](https://taginfo.openstreetmap.org/search?q=phone),  `phone` seem the preferred one 😉 
Anyway, HS should use both.

**Comment by tyrasd** [comment]
The osm wiki seems to agree with @pyrog's interpretation: https://wiki.openstreetmap.org/wiki/Key:contact

> For the most common keys, the shorter version outside the 'contact' scheme is used more frequently, over the time until now: phone=*, fax=*, email=* and website=*, with other contact tags used rarely outside the namespace scheme. Both schemes are in use for a long time and exist in parallel. Many applications are able to use both of them.
> 
> To limit tag fragmentation, consider using the most used keys.

In my personal opinion, the usage of `contact:phone` is fine for newly added phone numbers through healthsites.io. But if a feature already had a phone number mapped in the `phone` tag, healthsites.io should display it (and not show the _"please update phone number"_ placeholder) and should not change this already existing tag key when the phone number is updated by a user of healthsites.io.

**Comment by meomancer** [comment]
duplication of https://github.com/healthsites/healthsites/issues/1368
