### ISSUE TITLE
country boundaries

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#1302]
the country polygons need to be updated so that all facilities are included

![image](https://user-images.githubusercontent.com/38838/64633475-8bf74180-d3fb-11e9-9b20-582be9600392.png)

**Comment by meomancer** [comment]
hi @markherringer 
https://develop.healthsites.io/map?country=Senegal

could you check it in here and other countries?
if it is ok, i will implemented it to production

**Comment by meomancer** [comment]
this is fixed
