### ISSUE TITLE
attributes not appearing in Healthsites

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#1303]
As a registered user I expect to see the attributes loaded through healthsites to OSM visible in Healthsites. Currently the attributes are being published to OSM but not synced back in Healthsites.

https://healthsites.io/map#!/locality/way/26989989 - missing attributes listed below
https://www.openstreetmap.org/way/26989989

Missing attributes:
name - OLVG, locatie Oost
opening_hours 24/7
operator - Our Lieve Vrouwe Gasthuis (OLVG)
electricity -grid
health_amenity:type - ultrasound
healthcare - doctor;hospital

**Comment by meomancer** [comment]
this fixed
