### ISSUE TITLE
updates not appreaing in national or country updates list

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#1304]
Please confirm that updates made are published to 

Latest updates
https://healthsites.io/map?country=Netherlands

Latest updates
https://healthsites.io/#country-data

Please increase number of updates to scroll to 20
Please add 'previous' and 'next' links to the country 'latest updates'.

**Comment by meomancer** [comment]
could you test in here @markherringer 
https://develop.healthsites.io/map
