### ISSUE TITLE
shapefile note generating

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#1308]
https://gitter.im/healthsites/healthsites

Hello, Thanks for this great initiative! One comment: It seems that the creation of the download shapefile links is not working for some countries. Among others, for Bosnia Herzegovina and Czech Republic, but also the general link ("Download all healthsite data"). It gets stuck at "generating shapefile" for hours, and I have been trying it for several days.

**Comment by meomancer** [comment]
could you test in here @markherringer 
https://develop.healthsites.io/map

**Comment by timlinux** [comment]
@meomancer This for example is not working for me https://healthsites.io/map?country=France

**Comment by meomancer** [comment]
found the error (502)
i will fix it
