### ISSUE TITLE
can't zoom to individual locations and break a cluster of 9 locations down

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#131]
As a user I expect to see individual icons for each healthsite so that I can view the attributes of each healthsite

https://healthsites.io/map#!/locality/3dab329d2bdd4b3fbedf93746101dfbd

![9-cluster-no-zoom](https://cloud.githubusercontent.com/assets/38838/5214112/c009910c-760f-11e4-87c3-c818899f1775.png)

**Comment by smit1678** [comment]
To flag again, I'm seeing this on latest production and staging sites. Seeing on Chrome and Firefox. Several examples in Dar es Salaam with the clusters around this facility: https://healthsites.io/map#!/locality/fdca5ead9e9e4752aa444fe73c92e41c. 

Clicking the cluster centers the map but does not uncluster to allow you to access the separate locations.

**Comment by meomancer** [comment]
fixed
