### ISSUE TITLE
Unable to download shape files larger than 1GB

### ISSUE THREAD

**Issue by nixilla** [healthsites/healthsites#1323]
```
curl -O https://healthsites.io/media/shapefiles/World.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 50 2038M   50 1038M    0     0  2871k      0  0:12:06  0:06:10  0:05:56 2916k
curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)
```

**Comment by minjooya** [comment]
curl -O https://healthsites.io/media/shapefiles/World.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 50 2038M   50 1038M    0     0  2871k      0  0:12:06  0:06:10  0:05:56 2916k
curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)

**Comment by nixilla** [comment]
it seems that:

```
proxy_max_temp_file_size 4096M;
```

fixes problem - please confirm.
