### ISSUE TITLE
How it works copy

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#1340]
The Healthsites open data project is a resource for saving baseline health facility data to OpenStreetMap and improving the quality of health facility data through the interoperability OpenStreetMap provides

Interoperability between different information management systems and collaboration with different organisations through open data structures enables the maintenance of the data

![Healthsites-Architecture](https://user-images.githubusercontent.com/38838/74088445-dfe38080-4a96-11ea-9cc7-3753993fa4a5.png)

https://wiki.openstreetmap.org/wiki/Global_Healthsites_Mapping_Project
https://github.com/healthsites/healthsites/

**Comment by meomancer** [comment]
fixed
