### ISSUE TITLE
healthsites.io OSM editor should allow setting changeset comments & source

### ISSUE THREAD

**Issue by tyrasd** [healthsites/healthsites#1343]
currently, the OSM editor of healthsites.io doesn't allow users to specify a changeset comment, nor does it allow specifying a source of the respective edit.

Changeset comments are described here on the OSM wiki: https://wiki.openstreetmap.org/wiki/Good_changeset_comments

A changeset source should be specified, for example in order to distinguish contributions which are based on local knowledge from contributions which are based on a reference data set, etc. See https://wiki.openstreetmap.org/wiki/Key:source#How_to_use_on_changesets - Note that such source tags should typically not be set on individual OSM object.

**Comment by meomancer** [comment]
this is fixed by https://github.com/healthsites/healthsites/pull/1386
