### ISSUE TITLE
500 - Internal Server Error 

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#1350]
As a user I want to update the contact number of a Healthsite so that others can call the facility

https://healthsites.io/map#!/locality/way/-3600358

Error when uploading. Request failed: 500 - Internal Server Error - 500 Internal Server Error If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.

To load a number and test please go here:
https://www.google.com/search?q=Jeroen+Bosch+Ziekenhuis+hospital&oq=Jeroen+Bosch+Ziekenhuis+hospital&aqs=chrome..69i57j33.386j0j7&sourceid=chrome&ie=UTF-8

**Comment by meomancer** [comment]
hi @markherringer 
the error is from OSM
we can't update it because the healthsite is not longer in osm
https://www.openstreetmap.org/way/-3600358

and we haven't handle to clean the healthsites that are no longer in osm

**Comment by meomancer** [comment]
found way to prevent error 500
using this PR:
https://github.com/healthsites/healthsites/pull/1359

so it will check the node/way exist in osm, if not, it will show 404 error

**Comment by tyrasd** [comment]
> we can't update it because the healthsite is not longer in osm
> https://www.openstreetmap.org/way/-3600358

Is this really the case here? I believe the OSM element corresponding to the mentioned healthsite would be https://www.openstreetmap.org/relation/3600358, which is still present in OSM. I would guess that your import process indicates OSM relations by a negative id, which is not uncommon.

**Comment by meomancer** [comment]
this also fixed
