### ISSUE TITLE
make healthsites much more useful by extending search

### ISSUE THREAD

**Issue by gubuntu** [healthsites/healthsites#1377]
enable search by attributes e.g. respirator / ventilator (thinking covid-19)

And filtering by specific attributes e.g. number of beds

**Comment by markherringer** [comment]
Thanks @gubuntu please see https://github.com/healthsites/healthsites/issues/1363

**Comment by meomancer** [comment]
this is duplication of https://github.com/healthsites/healthsites/issues/1257
