### ISSUE TITLE
not abbreviate addresse

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#1381]
The rule in OSM is to not abbreviate addresses.
See  changeset 82308472,  way=28712045
addr:full=1825 E Warner Rd, Tempe, AZ 85284

The street name is different from the highway way 597611061 : East Warner Road. To my understanding, this might create problem with navigation tools.

**Comment by MarcoMinghini** [comment]
The use of addr:full is problematic, but there is an additional problem.

I made a quick check with a local pharmacy (https://www.openstreetmap.org/node/674123680), which already has its address correctly tagged with addr:street, addr:postcode, addr:housenumber, addr:city and addr:country.

This correctly-formatted assress is invisible to healthsites.io, which shows the Address field blank (see https://www.healthsites.io/map#!/locality/node/674123680)

**Comment by meomancer** [comment]
the address already splitted to street, postcode, housenaumber, city and country
https://github.com/healthsites/healthsites/pull/1387
