### ISSUE TITLE
include changeset comment

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#1384]
https://www.openstreetmap.org/changeset/82518254#map=20/-1.24450/36.66394&layers=H

**Comment by timlinux** [comment]
See #1385 

For the comments field help text:
Please provide any comments about this change. For example the mapping event, organisation programme or other rationale for these changes.

Let's validate the comment to ensure that it is at least 10 chars long (and explain to the user that it needs to be at least 10 chars) if validation fails.

Mark Herringer  7:10 AM
