### ISSUE TITLE
API specification doesn't seem correct

### ISSUE THREAD

**Issue by jeff303** [healthsites/healthsites#1411]
Greetings, I'm attempting to use the data from HealthSites for a COVID-19 related project.  I'm finding the API specification [here](https://healthsites.io/api/docs/) doesn't seem to be correct.  For instance, try the "Interact" button for the `GET /api/v2/countries/autocomplete` method there.  It results in an `HTTP 400 Insufficient characters` error from the server.  I observe the same thing when attempting to interact from Python.

```
from coreapi import Client
client = Client()
schema = client.get("https://healthsites.io/api/docs/")
result = client.action(schema, ["api", "v2", "facilities", "autocomplete", "list"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/coreapi/client.py", line 178, in action
    return transport.transition(link, self.decoders, params=params, link_ancestors=link_ancestors)
  File "/usr/local/lib/python3.7/site-packages/coreapi/transports/http.py", line 386, in transition
    raise exceptions.ErrorMessage(result)
coreapi.exceptions.ErrorMessage: <Error: 400 BAD REQUEST>
    message: "Insufficient characters."
```

There doesn't seem to be any way to specify the search term here.  I tried a variety of options (by including `params={'q': 'Hospital'}` as the last argument to `client.action`, but couldn't find a parameter name that was accepted.

When checking the requests being sent from the [Map site](https://healthsites.io/map), I can see that the correct URI appears to be: `https://healthsites.io/api/v2/countries/autocomplete/e?q=SearchTerm`

And, in fact, that works fine in Python as well (using the built-in `requests` library).

```
import requests
res = requests.get('https://healthsites.io/api/v2/countries/autocomplete/e?q=Unit')
res.json()
[{'label': 'United Arab Emirates', 'id': 348}, {'label': 'United Kingdom', 'id': 349}, {'label': 'United States', 'id': 350}]
```

Can anyone explain the discrepancy I'm seeing here?  Thanks in advance.

**Comment by timlinux** [comment]
@jeff303 Sorry for the delay in getting back to you. I am going to ask our resident guru (@meomancer) to take a quick look.

**Comment by meomancer** [comment]
the fix is here : https://github.com/healthsites/healthsites/pull/1429

**Comment by jeff303** [comment]
When will this change be reflected in the production API?  I am still seeing this behavior:

```
>>> result = client.action(schema, ["api", "v2", "facilities", "autocomplete", "list"], params={'q': 'Hospital'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jeff/.local/share/virtualenvs/hospitalaid-Yme3N8YY/lib/python3.7/site-packages/coreapi/client.py", line 165, in action
    _validate_parameters(link, params)
  File "/Users/jeff/.local/share/virtualenvs/hospitalaid-Yme3N8YY/lib/python3.7/site-packages/coreapi/client.py", line 80, in _validate_parameters
    raise exceptions.ParameterError(errors)
coreapi.exceptions.ParameterError: {'q': 'Unknown parameter.'}
```

I assume there is some delay associated with this making its way from development into production.  Thanks for your help so far!
