### ISSUE TITLE
Latest updates

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#1425]
The latest updates are not being published. Please review

https://healthsites.io/#country-data

Latest updates
3 April 2020 09:13:28 - @Erwin Yosua - No Name amended
3 April 2020 09:12:14 - @Kovirii - El Paso Behavioral Health System amended

https://healthsites.io/map?country=Senegal

Latest updates
28 February 2020 13:32:33 - @Tahirou_D95 - Poste de santé de Mboundoum Barrage added
23 February 2020 18:51:30 - @malickhane - No Name added

https://healthsites.io/map?country=Philippines

Latest updates
3 March 2020 17:44:26 - @DearPaulPH - General Mariano Alvarez Hospital amended
3 March 2020 17:44:26 - @DearPaulPH - GMA Hospital amended

https://healthsites.io/map?country=Ghana

Latest updates
2 March 2020 15:22:55 - @Arnson - Adaa chops compound added
2 March 2020 14:24:02 - @magma18 - No Name added

**Comment by meomancer** [comment]
The error was the docker osm down
already fixed
