### ISSUE TITLE
Create special user on HS that will not post the data to OSM

### ISSUE THREAD

**Issue by meomancer** [healthsites/healthsites#1455]
# Problem
We need an indicator for a special user that will not post payload into osm

# Solution
- [x] Make the special user configurable
- [x] Make every payload from the special user to be sent to sentry
- [x] Cut every process (just return the response after that)

**Comment by nixilla** [comment]
As a special user - configurable via settings.py
In order to test integration without changing OSM live data
I want to be able to post to API and see my payload in Sentry
