### ISSUE TITLE
we need to create and use official social_auth tokens

### ISSUE THREAD

**Issue by dodobas** [healthsites/healthsites#146]
at the moment we are using developer social_auth tokens, we should create official ones and integrate with the services 

facebook - https://www.facebook.com/healthsites.io
Google - https://plus.google.com/u/2/117257570769390062756
Twitter - https://twitter.com/sharehealthdata
Linkedin - https://www.linkedin.com/company/healthsites-io?trk=biz-companies-cym

**Comment by meomancer** [comment]
@markherringer 
i need access to get authoken for each  of account

**Comment by meomancer** [comment]
impediment (live site error, but staging not, just facebook and twitter wre working in live)

**Comment by meomancer** [comment]
Version 2 is just using osm social auth and already works
