### ISSUE TITLE
can't add new healthsite

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#1463]
Normal course:

- Login to https://healthsites.io/
- click 'Add new'
- complete form
- complete changset form
- submit

The new site is not added. The page hangs as pictured in the attached screenshot

![Screenshot from 2021-01-06 21-26-17](https://user-images.githubusercontent.com/38838/103817191-7aad5c00-5066-11eb-8676-3d40457c8683.png)

**Comment by nixilla** [comment]
Mark, really?!
