### ISSUE TITLE
geoserver electricity layer

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#1464]
As a healthsites user I would like to see the electricity supply layer so that I can see which healthsites could have electricity

https://wiki.openstreetmap.org/wiki/Power_networks

**Comment by meomancer** [comment]
For this i think we need to add "Overlay Features"
So we can add others layer too easier (without development)
And maybe we can put it on geoserver

Please check this ticket
https://github.com/healthsites/healthsites/issues/1483

CC @markherringer @timlinux 
I will close this as per we have epic ticket for this
