### ISSUE TITLE
API Updates

### ISSUE THREAD

**Issue by timlinux** [healthsites/healthsites#1499]
Currently we have our API at https://healthsites.io/api/docs/
The current version of the API is V2.

Our new V3 API will require enrollment so that we can:

*  measure and rate limit usage if needed
* contact our API users with service announcements (e.g. adding / removing / changing / deprecating end points)
* understand our user base
* support requests for funding by demonstrating who and by which organisations the API is used
* prevent abuse of our limited resources
* identify parts of the API that can be optimised (e.g. cached on the backend)

The proposal is thus to introduce V3 of the API which will provide the same calls but require a valid token in order to use it.

We will add an enrollment form which will include the following fields:

* contact person (full name)
* contact email
* organisation
* organisation URL
* web site or project URL for API will be used

In addition we will automatically capture the following data:

* enrolement date
* approved (we need an admin UI where we can approve API access requests)

Whenever an API request is made, we should log the request:

* date (to day level)
* API key holder ID
* endpoint e.g. /api/v3/countries/autocomplete
* counter (number of requests made for the current day)

The current API (v2) shall be updated to return a message for each request:

"This API is deprecated, please upgrade your application to use v3 of the API and register for your API token at URL"

cc @markherringer

**Comment by meomancer** [comment]
Tasks:
- [ ] Move v2 api to v3 api
- [ ] Create "This API is deprecated, please upgrade your application to use v3 of the API and register for your API token at URL" message to v2
- [ ] Move api-key as parameters to token based
- [ ] Create enrollment model
- [ ] Create api request log model
- [ ] Create enrollment form

**Comment by meomancer** [comment]
Questions:
- Making the API limited by number of request per day, are we moving the map to be private too? Or is it still be able to be accessed unlimited and public? Because api are also being used by user
- Do we need user to login to get the api (through enrollment and api key is linked with user)? 
  If no, we need to exclude all of POST API for non logged in user (just using api key)

**Comment by timlinux** [comment]
@meomancer : 

| Making the API limited by number of request per day, are we moving the map to be private too? Or is it still be able to be accessed unlimited and public? Because api are also being used by user

Map needs to remain public. Maybe we need to organise the API to have private parts and public parts. Private parts are only used by the app, public are parts that need enrollment.

| Do we need user to login to get the api (through enrollment and api key is linked with user)?

I would say not needed since we get their details in the form anyway.

| If no, we need to exclude all of POST API for non logged in user (just using api key)

For POST API we already have an enrolment requirement right?

The users wanting POST API access need a lot of scrutiny because we are enabling them to write to OSM so it has to be linked to their OSM account and we need to ensure access is not used to abuse OSM.

**Comment by meomancer** [comment]
TODO:
- Allow POST API if the user that linked to api-key is already linked to osm
- Make all api on frontend public
- Make download shapefile needs to login first

**Comment by timlinux** [comment]
Some further notes:

* Core functionality needs no log in
* Downloading shapefiles needs log in - and we should implement counter to measure how many downloads each user does.
* Currently there will be no limit to the number of shp extracts each user can do, but we will use metrics from above to track if heavy users are making an unfair load on the platform and implement limits accordingly if needed.
