### ISSUE TITLE
as a healthsites administrator I want to know which facilities have contact numbers that are ready to dial

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#165]
how can we write code that checks the validity of a number?
for example:
if country code is +27 , area code is 21 and number 55567890 then > +272155567890 and status GREEN

Questions:
what are the international dialling codes for each country?
what are the area dialling codes within each country?
how many numbers are expected in each specific number..8?
How many numbers expected in the full number..10?

**Comment by meomancer** [comment]
we can't do that because our data is from osm
