### ISSUE TITLE
As an administrator I want to import locations from OSM 

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#176]
Global OSM import on the healthsite attribute list.

@/all OSM data for healthsites https://drive.google.com/file/d/0By5d_LnUO8lOZlJLamxEbnJpN0U/view?usp=sharing

Attributes to import:
https://github.com/healthsites/healthsites/wiki/Healthsite-attributes

This is how we did the import for Konektaz. 
https://github.com/konektaz/where-is-when-is/commit/cacd4117b5147f1d3272faf72331717499d80701

http://www.overpass-api.de/query_form.html

http://overpass-turbo.eu/

**Comment by meomancer** [comment]
we don't need this as per version 2, the source of data is from osm
