### ISSUE TITLE
as a user I want to know the telephone number of a clinic is accurate because I see a link

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#178]
build rules that enable a link to appear when the correct ..
*International code
*national dialling code 
*number of digits
are present.

ie. for Cape Town South Africa

+27214567893

The user should be able to click the link from a smartphone and have the number ready to dial.

http://trafficlive.com/
<div class="phoneHeader">

```
<span class="ico-zg-iphone menu_icon" style="float:left;"></span>
<a id="telUS" class="telephone" href="skype:18007302620"></a>
<a id="telAU" class="telephone" href="skype:0296998365"></a>
<a id="telGB" class="telephone" href="skype:08008803002" style="display: block;"></a>
```

</di

**Comment by meomancer** [comment]
now it is based on the osm contact tag
