### ISSUE TITLE
As an administrator I want to hide a location so that the data can not be accessed

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#181]
See pg 81 in the Professional Standard for Protection work. Also while it might focus on personal data, there may be some principles that apply to healthcare facility locations. http://publications.iom.int/bookstore/free/IOMdataprotection_web.pdf#page=12

.. risk of retaliation to health facilities, healthcare workers and patients in areas if conflict is good context about what the health sector is facing in some parts of the world

**Comment by meomancer** [comment]
currently we are using osm data which is open data
