### ISSUE TITLE
geoname and location name search

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#183]
As a user I want to use predictive text to search for places on the map.

predictive text should allow the user to search geonames and location names.

Once selected the user should be taken to the map and presented with the healthsite or geoname location if selected. 
If healthsite then present healthite info in sidebar.
If Geoname then present a list of healthsite locations found within this geoname polygon:
[Geoname] healthsites
Hospitals: XXXXX
Clinics: XXXX
Orthopaedic clinics: xxxx

**Comment by markherringer** [comment]
http://www.geonames.org/export/client-libraries.html

**Comment by meomancer** [comment]
note for me :
- [autocomplete, based on = healtsite & place (geonomes)]
- [redirect to map if it is selected]

**Comment by markherringer** [comment]
Geoname search

![jakarta-search-auto](https://cloud.githubusercontent.com/assets/38838/11422625/770bca20-9435-11e5-9e98-fbc9c2f0b356.png)

**Comment by markherringer** [comment]
Geoname result

![jakarta-search-result](https://cloud.githubusercontent.com/assets/38838/11422638/8fb10892-9435-11e5-9c1e-068a2a1a299f.png)

**Comment by meomancer** [comment]
@markherringer 
for geonome, i think we need the design from maria too
and also, the service for geonome is not ready yet, and it is related with https://github.com/healthsites/healthsites/issues/243

**Comment by meomancer** [comment]
for filtering healthsite based on geonome, we need a data that contain all of name of geoname that has polygon
@timlinux @markherringer 
for country, i use other project that just has country on them

is @ismailsunni has idea?
