### ISSUE TITLE
Rwanda locations showing double

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#184]
While trying to update the database with additional fields in the script:
https://github.com/konektaz/healthsites/wiki/Rwanda-data
{
    "uuid": "uuid",
    "upstream_id": "ID",
    "geom": ["Lon", "Lat"],
    "attributes": {
        "name": "Health Facility",
        "physical_address": "Address",
        "http://moh.gov.rw": "Source of info"
    }
}

we ended up loading the locations twice. Zooming in to a single location to view location details is impossible. 

From initial discussions with Tim it sounds like we will need to Geocode a location drop/delete command to just remove all the locations for Rwanda. This will allow us to load the new script.
We need to be able to delete and replace locations.

**Comment by meomancer** [comment]
we are using data from osm now
