### ISSUE TITLE
As an admin I need to easily identify the health locations in a country

### ISSUE THREAD

**Issue by ismailsunni** [healthsites/healthsites#194]
We need an admin page to do this. Things that we need:
- [ ] Country data : to be used in querying the health locations. Then we need to add country model.
- [ ] Admin page that shows list of health locations in a country
- [ ] Add, update, delete functionality for each health location
- [ ] Add and delete health sites for a whole country (the update will be happened in spreadsheet)

@markherringer please add if I miss something.

cc @timlinux

**Comment by markherringer** [comment]
This looks good. The way we will get data to begin with will be in the form of .csv files that will be given to us.  In the same way as the data from the Rwanda FOI request. It is important that we acknowledge the source of the data (Health Ministry of Rwanda)  and date time stamp it. This establishes a level of acceptance regarding the validity of the data. We could call this Phase 1 location data upload.
Add, update, delete functionality for each health location is a feature that will form part of the location validation framework. We could call this part of Phase 2 location upload and validation.
