### ISSUE TITLE
As an admin I need to know that each location will be visible and have a unique ID

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#198]
Supporting user story:
As an admin in need to be able to:
1) Load a list of NEW locations
2) update a list of EXISITING locations
3) replace a list of EXISITING locations

When uploading a list of locations there is a possibility that a clinic AND a hospital can have the same lat/long
In this case the two 'locations' will be published under the same front end icon with the 'number 2' above it. The user will not be able to access either.

We need to be able to manage this duplicate situation
Option 1
Catch the list of duplicates and then make an amendment to make both locations accessible.

Option 2*
Change the rule so that should duplicates be found a minimal amendment is made to the lat/long.

'Healthsites - Data Loader

You have successfully load data

There are 457 localities created and 0 localities modified. You also have 49 possible duplicated localities, and they are not added.'

https://www.lucidchart.com/documents/edit/d2fa4656-d12e-491e-8b33-f36d44c13646?shared=true

**Comment by markherringer** [comment]
'ok so in previous system, we have only uuid and upstream_id to find a existing locality.

The UUID is generated if not available in the CSV, and it's a random hexadecimal string.
The upstream_id is concatenation between organisation_name and the ID. E.g. Siera¶HF0999

I check in 3 of your sample data, they don't have UUID column.

It means, we only have upstream_id to check duplications. Meanwhile, organisation_name is typo-able. We can have duplication if we mistype the organisation name.

**Comment by meomancer** [comment]
we already have uuid
