### ISSUE TITLE
as a user viewing a location I want to know when the location was last modified

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#199]
as a user I want to know when a locations attributes were last modified so that I can make an accuracy assesment

We need to publish the date and time of the modification of the data
https://github.com/konektaz/healthsites/wiki/Core-attributes-for-Health-facilities

date_modified

Overview:
The data being loaded may have a date time stamp of when it was created. For instance a Health Ministry may conduct an audit every two years. 

date_created

We may want to add our own 'date time stamp' indicating when an attribute was 'first loaded' to the healthsites system.

question:
Will we keep a log of every attribute for every location?

**Comment by meomancer** [comment]
already done with changeset
