### ISSUE TITLE
data visualisation

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#201]
As a hospital data administrator I want to see a visual representation of my hospital data so that I can see where to improve.

![datavis](https://cloud.githubusercontent.com/assets/38838/9252805/3f9532d0-41d2-11e5-8c65-d437082f82a9.jpg)

we need to establish a data model based on the administrative boundaries of a country. This will allow provincial/regional views to be taken of the data completeness of the location attributes:
ie . geom, name, type, services, date_modified, physical_address, contact_person, phone, mobile, email, url

**Comment by meomancer** [comment]
Already has statistic of a country and also the shapefile can be downloaded
