### ISSUE TITLE
merge the trusted partner data with OSM data?

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#214]
as a administrator I need to see a list of possible location duplications so that I can consider potential merging opportunities

Include a source sidebar on the map so that the user can select the source to display.
![kibera-vs-national-data](https://cloud.githubusercontent.com/assets/38838/10242593/c734d96e-68e9-11e5-964b-4f45a6839eaa.png)

**Comment by meomancer** [comment]
version 2 using osm data and API already handle duplication
