### ISSUE TITLE
Twitter login broken

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#215]

**Comment by ismailsunni** [comment]
Problem
-----------
After log in with Twitter, it redirects to wrong url. It should be `healthsites.io` but it's redirect to `healthsites` only. I have done some inspections:

- In Twitter Apps
I thought in the twitter apps, it sets the redirect url. I have even created new app, but it still doesn't give the right redirect URL
- In nginx configuration
Nothing is strange. All is set to healthsites.io. Nothing is mentioning `healthsites` only
- In django code
I have checked my python-social-auth document, and there is nothing that mention set redirect url

This is working in my local deploy...

**Comment by ismailsunni** [comment]
Following the tutorial from python-social-auth here: http://python-social-auth.readthedocs.org/en/latest/backends/twitter.html.
I set the call back URL to `http://staging.healthsites.io/complete/twitter`. But it will give you `http://healthsites/complete/twitter` (without the `.io`). It will give you an error, of course.

I also tried to hack the python-social-auth like in https://github.com/omab/python-social-auth/issues/713 (because, once I got 401 also). But, it doesn't give a better result.

**Comment by markherringer** [comment]
What was the old configuration? This was working. Can we see the old code?

**Comment by markherringer** [comment]
http://stackoverflow.com/questions/32460547/python-social-auth-redirect-to-wrong-url

**Comment by timlinux** [comment]
On marks old site we got this though I don't know if it is relevant.

```
SSLHandshakeError at /accounts/twitter/login/
[Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
Request Method:	GET
Request URL:	http://www.konektaz.info/accounts/twitter/login/
Django Version:	1.4.2
Exception Type:	SSLHandshakeError
Exception Value:	
[Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
Exception Location:	/home/webdeploy/sites/konekta.info/env/local/lib/python2.7/site-packages/httplib2/__init__.py in connect, line 1037
Python Executable:	/home/webdeploy/sites/konekta.info/env/bin/python
Python Version:	2.7.3
Python Path:	
['/home/webdeploy/sites/konekta.info/repo',
 '/home/webdeploy/sites/konekta.info/env/bin',
 '/home/webdeploy/sites/konekta.info/env/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg',
 '/home/webdeploy/sites/konekta.info/env/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg',
 '/home/webdeploy/sites/konekta.info/env/src/django-mptt',
 '/home/webdeploy/sites/konekta.info/env/lib/python2.7',
 '/home/webdeploy/sites/konekta.info/env/lib/python2.7/plat-linux2',
 '/home/webdeploy/sites/konekta.info/env/lib/python2.7/lib-tk',
 '/home/webdeploy/sites/konekta.info/env/lib/python2.7/lib-old',
 '/home/webdeploy/sites/konekta.info/env/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-linux2',
 '/usr/lib/python2.7/lib-tk',
 '/home/webdeploy/sites/konekta.info/env/local/lib/python2.7/site-packages',
 '/home/webdeploy/sites/konekta.info/env/local/lib/python2.7/site-packages/PIL',
 '/home/webdeploy/sites/konekta.info/repo']
```

**Comment by markherringer** [comment]
I would like to compare the server set ups for konektaz.info and healthsites.io
The issue we're currently experiencing on konektaz concerns a failed certificate whereas the healthsites.io issue described above is different. Oauth is directing back to 'healthsites' not 'healthsites.io'

Therefore, my suggestion is to compare the server set ups of the two and look for the difference.

**Comment by nixilla** [comment]
I just installed latest version on my local VM. Twitter auth is working. I presume there is some issue with prod configuration.

**Comment by markherringer** [comment]
![twitter-login](https://cloud.githubusercontent.com/assets/38838/11221356/a032d5d6-8d5c-11e5-8317-3313fcbda474.png)

**Comment by markherringer** [comment]
![twitter-login-profiles](https://cloud.githubusercontent.com/assets/38838/11221407/e1ab40e8-8d5c-11e5-8e8d-574e58067f47.png)

**Comment by timlinux** [comment]
Please read the log messages from gitter - as I have explained there I believe this is caused by the reverse proxy in front of the site.

One option (sledgehammer fix) would be to deploy on a server without a reverse proxy (which means the server would only be able to run a single site easily). But I believe we can fix the reverse proxy issue - I just need to have a bit of time to look into it.

**Comment by nixilla** [comment]
@timlinux the reverse proxy you are referring is not the part of the project. Therefore we're not able to replicated it. The develop version at http://healthsites.134.213.210.219.xip.io is also behind the reverse proxy which looks like this:

```
server {
  listen 80;
  server_name cittadelcapo.com;
    location / {
      access_log off;
      proxy_pass http://localhost:49361;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
```

Can you share your configuration so we can test it?

Apart from this nginx config everything else is running as prod_docker on http://healthsites.134.213.210.219.xip.io therefore I'd say this ticket is invalid.

**Comment by meomancer** [comment]
@markherringer should we move to done?
