### ISSUE TITLE
completeness of attributes

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#241]
what percentage of locations within a region (planet, country) have basic, partial or complete records?

See completeness of attributes
https://redpen.io/tf7e333aa64827242d

Basic - Mandatory attributes only
Partial - Some Core attributes present
Complete - All attributes complete

The country data section works off the map to the left of the page.
The default state is the whole planet
Should the user search for and select (using predictive text) a country then the Country data will display data for the selected country.

Healthsites attributes:
https://github.com/healthsites/healthsites/wiki/Healthsite-attributes

See healthsite location with attributes:
https://redpen.io/pad27ff5d21e1fa7f7

So for example what percentage of healthsites in the UK have Basic - Mandatory attributes only.

**Comment by meomancer** [comment]
already implemented, but the attributes has changed based on osm tags
