### ISSUE TITLE
establish country data section

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#243]
https://redpen.io/ed70300c042811388e

Normal course:
The user will scroll down the page and find the map and the graphs showing how the data breaks down.
The map will show data that relates to the graphs.

Default view:
See all data for all countries.
Map will be doomed out.
When a user clicks on the map zoom in so that the locations can de-cluster
Allow a user to drag and move the map.
When the user clicks on an individual location open the map page and location sidebar for that location.

Country view:
The user wants to look at data for a specific country.
Type country name..
When the user starts typing present the top 5 auto-completed options in a drop down so that they can select. See google.

Once selected open the map for selected country and display corresponding data in the graphs. 
Show the locations on the country data map

**Comment by meomancer** [comment]
@markherringer 
for this card, the first thing is :
- getting country data
- making autocomplete for country

**Comment by meomancer** [comment]
![screenshot from 2015-12-02 17 22 49](https://cloud.githubusercontent.com/assets/4530905/11528460/759bf7a8-9919-11e5-9b9b-e1fac90e3947.png)
![screenshot from 2015-12-02 17 22 58](https://cloud.githubusercontent.com/assets/4530905/11528458/759b960a-9919-11e5-888a-3db9c9c6860e.png)
![screenshot from 2015-12-02 17 23 08](https://cloud.githubusercontent.com/assets/4530905/11528461/759fca36-9919-11e5-9bb2-11d0024265ca.png)
![screenshot from 2015-12-02 17 23 19](https://cloud.githubusercontent.com/assets/4530905/11528459/759ba6a4-9919-11e5-8115-1149be443e25.png)
![screenshot from 2015-12-02 17 23 33](https://cloud.githubusercontent.com/assets/4530905/11528462/75a0681a-9919-11e5-91ae-ef504d4bc9e3.png)

**Comment by meomancer** [comment]
![screenshot from 2015-12-04 18 04 14](https://cloud.githubusercontent.com/assets/4530905/11588325/1ee82a04-9ab2-11e5-8a0c-96222776ffb2.png)
![screenshot from 2015-12-04 18 04 35](https://cloud.githubusercontent.com/assets/4530905/11588324/1ee61908-9ab2-11e5-9dce-6e7202e2149f.png)
![screenshot from 2015-12-04 18 04 45](https://cloud.githubusercontent.com/assets/4530905/11588326/1eeb6f5c-9ab2-11e5-9251-49492cf52e3a.png)

**Comment by meomancer** [comment]
@MariaSolovyeva already fixed the layout

![screenshot from 2015-12-07 10 35 13](https://cloud.githubusercontent.com/assets/4530905/11618519/8ce2ece2-9cce-11e5-9d58-84fe8f4b4a76.png)
![screenshot from 2015-12-07 10 35 21](https://cloud.githubusercontent.com/assets/4530905/11618518/8ce06cb0-9cce-11e5-9aff-0ceeda789265.png)
![screenshot from 2015-12-07 10 36 14](https://cloud.githubusercontent.com/assets/4530905/11618520/8d101686-9cce-11e5-9e4c-2a9e6080434c.png)
