### ISSUE TITLE
update docker instructions

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#249]
INFO[0000] Error: image konektaz/healthsites:latest not found

change : konektaz/healthsites 
to : healthsites/healthsites

**Comment by rsaameli** [comment]
HI Mark, thnaks for the chat today. Can you please remove my private emails (rsaameli@gmail.com and rene_saameli@yahoo.com)  from this mailing  group as my mailbox is totally spammed...many thanks cheers, 
 ..................................................... René Saameli Ch.de la Fin du Clos 20 1616 Attalens  rsaameli@gmail.com

**Comment by meomancer** [comment]
all can be done by "make deploy"
