### ISSUE TITLE
contact us form

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#256]
A Google form like we currently have on  http://healthsites.io/ in the about section

Name
email
Message

On submit present confirmation message:
Thanks! You can also reach us [here](https://gitter.im/healthsites/healthsites)

**Comment by meomancer** [comment]
@markherringer 
where do you prefer the button for contact us  place? or should be like old site? which is in about section?

**Comment by markherringer** [comment]
![contact-us-form](https://cloud.githubusercontent.com/assets/38838/11268157/5eae0562-8ea7-11e5-9c93-bb76e778893e.png)

**Comment by markherringer** [comment]
Use the 'Contact us' links in the 'Share the healthsite data' section of the blue bar and the 'Contact' link in the footer

**Comment by markherringer** [comment]
https://okfn.org/privacy-policy/
