### ISSUE TITLE
tag a location with a keyword

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#266]
as a user I would like to associate a keyword with a location that is not on the list

FGM

**Comment by markherringer** [comment]
Hi Irwan, if the user does not find the attribute on the drop down we provide, let them specify it in a text field.

**Comment by meomancer** [comment]
@markherringer is it for this tag? Because for editing, i don't make dropdown. I just use simple edit as in screenshot.
Because i don't know the UI would we like to approach

**Comment by meomancer** [comment]
@markherringer already fix and push staging
