### ISSUE TITLE
define operating hours

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#267]
as a user I want to specify the operating hours of a healthsite

Monday -Thursday – 09.45-12.00 and 13.00-16.30
Friday – 09.45-12.00 and 13.00-16.15

Exceptions
Name of exception

Monday - Friday: 07.30-22.30 (22.00 close during Summer). Closed bank holidays. 

Saturday/Sunday: 09.00-19.00 (17.00 close during Summer).

**Comment by markherringer** [comment]
Here is an page describing the challenge:
http://ux.stackexchange.com/questions/33600/form-for-inputting-operating-hours-of-a-business

**Comment by meomancer** [comment]
@markherringer already fix and push staging
