### ISSUE TITLE
Developers

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#278]
Ensure links are visible
Remove the API link..maybe we should link to a WIKI page describing the envisaged API @timlinux?

**Comment by timlinux** [comment]
Yes lets remove it for now

**Comment by MariaSolovyeva** [comment]
Hello @markherringer ,  could you provide me and correct with the urls where the CTA links should lead to?

*Upload form
*Contact us
*Developers
*GitHub - https://github.com/healthsites
*Road Map
*Chat space - https://gitter.im/healthsites/healthsites

**Comment by markherringer** [comment]
Healthsites - sitemap

https://docs.google.com/spreadsheets/d/19m7Ck352PZ2E6MeWk6vKqGB47W5Y1wYX-9a4nP3JYps/edit?usp=sharing
