### ISSUE TITLE
healthsite geoname

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#281]
As a user I would like to know the geonames associated with the latitude and Longitude of a location

Question:
Given that we are not collecting the 'physical address' of each location should we rather import the Geoname associated with the point?

![location-data-sidebar](https://cloud.githubusercontent.com/assets/38838/11020206/1e8b4f84-8610-11e5-98b7-509f621d6cad.png)

**Comment by brenb** [comment]
Why has it been decided to exclude physical address?
