### ISSUE TITLE
animation

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#282]
as a user I want to be able to swipe through the animation in either direction so that I can study each stage in my own time

Note:
The animation should NOT autoplay

**Comment by MariaSolovyeva** [comment]
Hello @markherringer , you mean to add "next" and "previous" arrows?

**Comment by markherringer** [comment]
yes, something that allows the user to step through the screens. and see where they are in the order.

**Comment by markherringer** [comment]
Check to see if we casn use thumb-swipe on mobile
