### ISSUE TITLE
how it works - discovery

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#289]
Overview:
It needs to be super easy for users to 'discover' health care locations in their area. We do this through the 'search tool' and should consider enabling the 'find locations in your area' feature which geo-locates the user and presents locations nearby. 

In addition we could consider giving the health care location itself a twitter handle that is prominent so that users can communicate that way. Request a call back? This could be a way we address the spam issue.

Review attribute completeness in your area.
Earn points by improving attribute completeness in your area.
Using social media users are able to collaborate (maybe with community health care champions) and update attributes/access health care.

**Comment by meomancer** [comment]
it's been changed
