### ISSUE TITLE
as a healthsite administrator I want to know that healthsites is up to date with OSM

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#290]
As an administrator i want the system to run a healthsite query on OSM daily so that i know healthsites is up to date with OSM

Cron job
/etc/cron.daily

**Comment by brenb** [comment]
How are diffs applied?
In the scenario where healthsites has more attributes than OSM:
- Will updates made previously to an entity's healthsites-only attributes be left unchanged should updates be detected for the entity from OSM?

**Comment by meomancer** [comment]
we are using osm data for version 2, so this ticket is done
