### ISSUE TITLE
Load Data from Admin Page

### ISSUE THREAD

**Issue by ismailsunni** [healthsites/healthsites#291]
Problem
-----------
Currently, we only able to load data(CSV and json mapping file) from load form (currently not accessible for now, due to work in UI).

We need to load the data from admin panel also, see http://staging.healthsites.io/admin/localities/dataloader/add/

Optional Solution
----------------------
Perhaps we can add new process to load the data when user add new record (use post save signal). See https://github.com/healthsites/healthsites/blob/develop/django_project/localities/views.py#L242 to see how the load data works.

cc @markherringer @timlinux

**Comment by meomancer** [comment]
@timlinux @ismailsunni 
the issue i face now is 
from admin side : 
the data for data loader is already saved, but in the load_data_task, the data is not there (in data loader db). 
form form on site :
It is working fine

i tested it using no celery (which is just python task)
everything is fine, from admin and site side.
