### ISSUE TITLE
as a user of healthsites I would like health site attributes to be weighted

### ISSUE THREAD

**Issue by brenb** [healthsites/healthsites#294]
Much of the data imported into healthsites for African countries as at Nov 12, 2015 shows health sites attribute completeness as 31.25% complete. I think this overstates the usefulness of what has been imported. Besides GPS coordinates and health site name very little else is complete.

**Comment by meomancer** [comment]
i think this ticket is done, if we need another method for weighting the site, we can open another ticket to disscuss the methods
