### ISSUE TITLE
open country on map

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#307]
as a user viewing 'country data' on the home page I would like to click through to the map so that I can continue my investigation of this area

Normal flow: 
User types Rwanda into Country search field on home page
Rwanda map/polygon and associated locations and statistics presented
Map is clickable and opens either Rwanda polygon or the location if selected
http://staging.healthsites.io/map#!/locality/e274eeec396e41f08fc4c080713e6832

**Comment by meomancer** [comment]
It is already implemented in this card:
https://github.com/healthsites/healthsites/issues/243
