### ISSUE TITLE
make sure HTML assets are up to date on staging

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#308]
Update design assets on http://staging.healthsites.io/ so that they reflect http://healthsites.mashastudio.net/

Ideally you should be able to update the CSS and HTML received from Maria. This will take care of the following issues:

1) change 'HEALTHSITES.IO' to 'healthsites.io' - DONE
2) Align strapline (A free, curated, global, canonical source of healthcare location data) - DONE
3) Update share icon - DONE
4) Update menu font - DONE

Search:
5) change 'health site' to 'healthsite' - DONE

About:
6) Change 'What is Healthsites.io' to 'About healthsites.io' - DONE
7) Update the font of the body copy in the about section - DONE

The blue bar section...make updates to..
8) Data model - TODO
9) Share the location data
10) Developers
11) Chat live

Country data:
12) Add map - The map should fit between the blue bar (no gap) and the grey of the Lifecycle section (no gap)

Lifecycle section:
13) Update the assets

Partners:
14) Center the partner logo's
15) Update the footer

**Comment by meomancer** [comment]
@markherringer already made PR
