### ISSUE TITLE
Upload form

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#309]
as a health care location data administrator I want to easily share location data with healthsites so that the data becomes more accessible.

Suggested share process:
Complete form and upload .csv file with locations to G-Drive

Save all form upload data to a spreadsheet

Fields:

Name (See healthsites.io contact form)
email (See healthsites.io contact form)
Message (See healthsites.io contact form)
Select file to upload (button and field, display file name once selected)
Link to [Google template spreadsheet](https://docs.google.com/spreadsheets/d/1zyMBszXAphi8Zt8Fx2h-nzUvSxAQy9M29AsyLBzVbLg/edit?usp=sharing)
[Questions?](https://gitter.im/healthsites/healthsites)
Agree to make the data available under an [ODbL](http://opendatacommons.org/licenses/odbl/) license (checkbox)
Submit button
Clear button

Notes:
Restrict upload size?
Captcha spam check?

http://ctrlq.org/code/19747-google-forms-upload-files
http://stackoverflow.com/questions/21013693/google-forms-file-upload-complete-example

Idea!
Place a link to the spreadsheet on the G-Drive underneath the share location data form. Visitors to the page will be able to see all the previous file uploads and access.

Site to reference for similar process:
http://www.waterpointdata.org/

**Comment by meomancer** [comment]
the attributes has changed, so this ticket is not relevant anymore
