### ISSUE TITLE
healthsites.io privacy policy

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#310]
Privacy policy
healthsites.io, trading as healthsites.io, is a Limited Company. It is incorporated in England & Wales as a company limited by guarantee, with company number 06155449. VAT Registration № GB 918945382. Registered office address: healthsites.io, 34 LOWER RICHMOND ROAD, SW15 1JP, London, United Kingdom

Home Privacy policy
healthsites.io collects no more data about you than most other websites. This policy describes our approach to your personal data. Contact details can be found on the contact page.

As a general rule, we use information we have collected about you for the purposes you supplied it — for example if you have ordered goods or services from us, then we will use it to help us supply those goods or services. We also use information we have collected to help us understand how the site is used in order to improve it or to design new services we might offer.

For our healthsite mapping application location uploads, edits are published, and except in very limited circumstances, will be a permanent part of this site. If you decide to add or edit a location you must keep this in mind.

Under the Data Protection Act, you may at any time request a copy of the information we hold on you (for which we may charge a small fee to offset our administration costs) by writing to us (see above).

This privacy policy will be reviewed, and may be revised, from time to time. You may wish to revisit it regularly.

If you have registered through a social media account, thank you for doing so, we appreciate your support. As a registered member you will be able to add and edit locations on the site. We will use information you supply us to help improve the quality of health care location data. We may use your social media account to get in touch.

Public data and publishing
Browsing this site doesn’t reveal your identity publicly, though see Private Logging later in this document for more information.

Author identification
When posting a comment or editing a location on the map, social media address will be required. You do not have to select your real name or use your regular social media address. By adding or editing a location you consent to publishing your social media account and associating it with the location. If you are concerned, you may wish to establish an anonymous account. However, healthsites.io factors in the identity of the social media account when determining the validity of the update. Therefore there is a good chance that the update by an anonymous user will be overwritten.

Page edits, comments, trackbacks, and pingbacks and other activity on our websites may be identified by your IP address. These numbers could potentially be traceable to identifying information about you, whether it is your home ISP or the University or Work account where the IP address is registered. Your IP address could potentially be used in conjunction with other data to identify you.

If you are concerned about attempts to match your IP address to your identity, you may wish to use an anonymous browsing service or attempt some means to obfuscate your real IP address.

If so, you might like to try Tor, an anonymous browsing service. Please see Tor for more details.

Email
If you have given us your e-mail address, you agree to allow us to send e-mail to that address in order to deliver our services to you. In practice this will usually involve emails about service down-time or important changes to services to which you subscribe. Some e-mails — such as those subscribed to mailing lists — will receive more traffic as an integral part of the service.

In addition to necessary e-emails, we will also occasionally use the e-mail to contact you for our own purposes. For example we might want to tell you about new services we are offering or we might be seeking volunteers for one of our many activities. We will only do so sparingly. We understand how annoying it can be to receive large quantities of unsolicited mail. We will do our best to ensure that anything we do send to you will be relevant and unobtrusive.

Cookies
Our sites may use cookies. This is often as a convenience for you to enable certain site features. You may wish to clear these cookies and the browser cache if you wish to refrain from revealing any identifying information, especially if you are using a public or shared computer. You may also wish to disable your browser from accepting cookies.

Private logging
Any time you visit a page on the internet, you send quite a bit of information to the server. The webservers that host this site maintain access logs with the information that you send. This information is used to provide site statistics and to get an idea of popular pages and what sites link here. We do not intend to use these logs to identify legitimate users.

The data logged may be used by us to solve technical problems with the site and, in cases of abuse of this site, to investigate the abuse.

We also use web analytics services to get a general idea of the kinds of traffic our websites get in order to provide better services and to set benchmarks for how we are doing in meeting healthsite.io's goals.

Again, if you are concerned about attempts to match your IP address to your identity, you may wish to use an anonymous browsing service or attempt some means to obfuscate your real IP address.

Data release policy
Our policy is only to release the data we collect in the following circumstances:

As required by law, such as in response to a valid request from law enforcement.
To designated third parties to resolve or investigate abuse complaints.
When the information is related to spiders or bots, usually when investigating technical issues.
For abusive users, we may release information to assist in attempting to block the abusive user or to complain to that user’s Internet Service Provider.
If necessary to defend legal claims against us by third parties.
When we deem it necessary to protect the property or rights of the user community, or this website.
No selling of information
We will not sell information collected via this site, such as your email address, to third parties.

Information security
We make no guarantee that the information that you provide us will be secure.

**Comment by meomancer** [comment]
now we are under license of osm
