### ISSUE TITLE
map error

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#324]

**Comment by MariaSolovyeva** [comment]
TypeError: this.$sidebar_body.offset(...) is undefined

...sidebar_body.height($(window).height()-this.$sidebar_body.offset().top-e)},getIn...

**Comment by MariaSolovyeva** [comment]
The map is visible only after the window side is changed

**Comment by meomancer** [comment]
@markherringer 
@timlinux 
already fixed in this PR : https://github.com/healthsites/healthsites/pull/325
