### ISSUE TITLE
Map div should not overlap the side panel

### ISSUE THREAD

**Issue by timlinux** [healthsites/healthsites#335]
The fix for the map display being hidden introduces a regression - the div for the map areas should extend only as far as the right side of the side panel. i.e. it should coincide with the red box below.

![selection_001](https://cloud.githubusercontent.com/assets/178003/11364989/3fe50fbe-92ac-11e5-84a0-7e9a4bc36fa7.png)

**Comment by meomancer** [comment]
i think it is fixed by @MariaSolovyeva
