### ISSUE TITLE
identify community users and champions through social media

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#337]
as a healthsites administrator I want to identify identify community users and champions through social media so that I can improve the adoption of healthsites in the field.

https://github.com/healthsites/healthsites/wiki/Healthsites-Android-Army

Normal course:
Arrive at healthsites.io
Register with linkedin profile
Confirm access to contact list and profile including endorsements and recommendations

**Comment by meomancer** [comment]
we are just using osm account now
