### ISSUE TITLE
Health site displays location name for another health site

### ISSUE THREAD

**Issue by brenb** [healthsites/healthsites#339]
![invalid_location_name_for_health_site](https://cloud.githubusercontent.com/assets/1570709/11390488/531e53e0-9353-11e5-8ca0-f2d23ba08e8c.jpg)

Health site in Zimbabwe (and many other countries where location name is missing in the data set) displays location name for health site in Rwanda. This looks like a display field that's not being initialised in the health site information panel.

**Comment by markherringer** [comment]
could you share the link to this healthsite @brenb ?

**Comment by markherringer** [comment]
I cannot replicate the issue you mention. We do not import locations without mandatory fields. healthsite [name] is mandatory:
https://github.com/healthsites/healthsites/wiki/Healthsite-attributes

**Comment by brenb** [comment]
Follow these steps:

1) To show that this health site in Zimbabwe currently has no District
info, refresh your browser, then visit
http://staging.healthsites.io/map#!/locality/2b38c9cfef1540f28a14165bc437a4c8

2 Visit a health site in Rwanda with District info eg
http://staging.healthsites.io/map#!/locality/21e3fae50c504cb2b5415dc3bee6a0a9

3) Return to the health site in Zimbabwe and you will see District info for
the Rwandan health site incorrectly displayed for the Zim health site
http://staging.healthsites.io/map#!/locality/2b38c9cfef1540f28a14165bc437a4c8

Looks like variables are not being initialised when you click to display
info on different health sites.

**Comment by markherringer** [comment]
ok. great thanks. I can see the issue now. The name changes but the district info stays the same.

**Comment by meomancer** [comment]
@markherringer @brenb 
i could reproduce it. That is because the old one didn't re-rendering the show panel again for default. That why when the information is not provided, the view is still in previous information.
I already made PR for this issue.
