### ISSUE TITLE
As an administrator I want to assign users as 'trusted'

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#34]
This feature will allow administrators the opportunity to delegate healthsite validation work to people familiar with the region.
In addition it will give us the opportunity to add credibility to the location data.

User story:
As an administrator I want to assign users as trusted so that I can trust them to load good data.

Normal course:
User makes contact through share data form.
Administrator returns email and arranges Skype call to discuss trusted user status and determine data source.
Admin requests contact with organisation to confirm user is authorised to share the data on behalf of the organisation
Administrator makes decision regarding trusted user status and associates organisation/s to the user profile using a drop down list.

**Comment by meomancer** [comment]
It is done 
can be add in here: https://healthsites.io/admin/social_users/trusteduser/
