### ISSUE TITLE
map-default-view

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#360]
as a user arriving on the default map page I would like to see how my country compares to other countries

![map-landing-page-sidebar](https://cloud.githubusercontent.com/assets/38838/11421942/d654eb02-942f-11e5-87ad-0f6c96a0349d.png)

users are able to view country scores. maybe we need a search field to filter / select the country..
users click on the country link to view country on map

**Comment by meomancer** [comment]
@markherringer 
i need @MariaSolovyeva design for this too

**Comment by markherringer** [comment]
we need to establish the country link and the percentage complete for each country
