### ISSUE TITLE
establish unique url for the geoname search result

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#379]
as a user I want to share a link to my geoname search results.

I expect to see
- [ ] a unique URL 
- [ ] graphs that present information about the specific geonamed area.
- [ ] the locations of healthsites within the geoname polygon

![8fb10892-9435-11e5-9c1e-068a2a1a299f](https://cloud.githubusercontent.com/assets/38838/11585605/318c9ee4-9a65-11e5-93e6-7fbd9b836939.png)

**Comment by meomancer** [comment]
linked with #80
