### ISSUE TITLE
as a user I want to be able to search the map by lat/long co-ordinates

### ISSUE THREAD

**Issue by brenb** [healthsites/healthsites#412]
I have received a spreadsheet of health site data including lat/long co-ordinates and would like to see if details resolve to a health site already plotted on the map.

I would like to search the map using lat/long co-ordinates to see if a health site is located in the place detailed in my spreadsheet.

My spreadsheet includes only health site name and lat/long co-ordinates. I'm curious to see where that point is on the map.

**Comment by meomancer** [comment]
# Solution
Add form latitude/longitude at the left-bottom of map
