### ISSUE TITLE
As a user I want to be informed if someone updates a health site I've added or updated

### ISSUE THREAD

**Issue by brenb** [healthsites/healthsites#419]
Should we add the following optional attribute to a health site:
- 'owner' = health site validator (HSV)- the person/institution that created or 'claims' responsibility for the health site

And possibly a new entity: health_site_rss, which records contact details for any HSV or user who wants to track changes to the entity.

**Comment by meomancer** [comment]
It is not relevant because we are using osm data and don't have "owner" attribute anymore
