### ISSUE TITLE
Search for a health site should clearly identify it on a map

### ISSUE THREAD

**Issue by brenb** [healthsites/healthsites#420]
Search for a health site does not clearly highlight which of the health sites displayed on the map is the one being searched for. Ideally it should be highlighted with an animated site marker icon.

![search_healthsite_does_not_distinguish_target_from_others_in-frame](https://cloud.githubusercontent.com/assets/1570709/11873380/da3992ea-a4e2-11e5-9cff-1fdef34b5f90.png)

**Comment by markherringer** [comment]
http://staging.healthsites.io/map#!/locality/94f586044cc94025bad70b0186ed46f6
