### ISSUE TITLE
Duplicates displayed in search health sites drop down list do not aid selection

### ISSUE THREAD

**Issue by brenb** [healthsites/healthsites#421]
More information needs to be displayed in the search health sites drop down list to help the user make a selection. eg add city name.

![search_healthsite_duplicates_in_dropdown_list](https://cloud.githubusercontent.com/assets/1570709/11873538/b6eedfb0-a4e3-11e5-8b73-ac07091eb2c7.png)

**Comment by meomancer** [comment]
We could add search using "in" indicator

King Hospital in Paris

# Solution
If there is "in", add geolocation check like place, and do boundary query from the result
