### ISSUE TITLE
Duplicate healthsite?

### ISSUE THREAD

**Issue by brenb** [healthsites/healthsites#443]
![duplicate_location_perhaps](https://cloud.githubusercontent.com/assets/1570709/12415087/488c8756-bea2-11e5-8bb0-257ed243ba93.png)

Note that the map is on maximum zoom - the plus for zoom is greyed out - but the marker indicates 2 sites to view.

The url for this location/view is http://healthsites.io/map#!/locality/25f55cca5b0f4f118c337c62c1321f2d

lat: 21.3676677, long: -26.2807967

**Comment by meomancer** [comment]
now we are using osm data and our create API already check duplication before push to osm
