### ISSUE TITLE
country url

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#454]
as a user I expect to be able to share a link to a country

Currently this url has the following form. 
http://staging.healthsites.io/map?country=Afghanistan

A user can get to country data in the following ways:

1) From the 'country data' section on the home page
2) From the country links on the map page
3) From the 'place' search form

In each case the user will be directed to a polygon outline of the country on the map page.
Only the selected country healthsite data will appear
The user will be presented with a micrograph for the country
The user will be presented with latest updates 
The user will have the opportunity to download the country healthsite data

**Comment by MariaSolovyeva** [comment]
Country page mock-up:
https://redpen.io/beea6f088c4df59a1f

**Comment by markherringer** [comment]
this ticket is looking good. are we able to add the polygon?

**Comment by meomancer** [comment]
@markherringer already add to staging, with polygon
