### ISSUE TITLE
geolocate me

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#468]
the user wishes to add a location close to where they are. They want the map to show them on the map.

For instance :
A user wants to add a location close to where they are.
A nurse in a clinic wants to add her clinic to the map.

Suggested design pattern
The user is geolocated within a country view. (http://staging.healthsites.io/map?country=Angola)
A red marker indicates their position in the same way as the add new location does.
The left sidebar is the same as the country view.

They then are able to add or edit a healthsite which will then open the form.
If they are not logged in they will first be direct to the social sign on service and then returned to the form.

https://redpen.io/mn9c5f1f7edc6c579d

**Comment by MariaSolovyeva** [comment]
Here are the couple of options

![add-healthsite1](https://cloud.githubusercontent.com/assets/10400420/12788192/b5ef3312-caa9-11e5-8505-4a4bb5a4d828.png)
![add-healthsite2](https://cloud.githubusercontent.com/assets/10400420/12788193/b61f3800-caa9-11e5-8d39-3eaadf8380ed.png)

**Comment by MariaSolovyeva** [comment]
I think that in this case the colored pin should serve good

**Comment by MariaSolovyeva** [comment]
HI @markherringer ,  were you talking about this kind of circle?

![add-healthsite3](https://cloud.githubusercontent.com/assets/10400420/12841032/525f833c-cbf9-11e5-8ca2-3b11e04221d2.png)

**Comment by markherringer** [comment]
Hi @MariaSolovyeva , yes. I think this last one is the way to go. what do you think @timlinux ?
