### ISSUE TITLE
Add HOTOSM logo to the partners section

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#476]
Place the logo on the right

Mouse over copy -  The Humanitarian OpenStreetMap Team 

Open new window - https://hotosm.org/

PLease use this logo:
https://wiki.openstreetmap.org/wiki/Humanitarian_OSM_Team_Logo

![1280px-hot_logo_with_text svg_](https://cloud.githubusercontent.com/assets/38838/12745948/cdd6d116-c9a4-11e5-8671-ab45d02c0357.png)

**Comment by MariaSolovyeva** [comment]
Hello @markherringer , do other logos need links too?

**Comment by markherringer** [comment]
Thanks Maria,

Here you go:
https://www.icrc.org/
http://healthcareindanger.org/hcid-project/
https://www.ihf-fih.org/
