### ISSUE TITLE
graphs not working on staging

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#482]
The graph is currently showing an equal number of hospitals, medical clinics and orthopaedic clinics

http://staging.healthsites.io/map?country=Angola

**Comment by meomancer** [comment]
@markherringer could youelaborate with some detail?
because i could see that the graphs is working fine

![screenshot 4](https://cloud.githubusercontent.com/assets/4530905/12770946/987f5372-ca57-11e5-9c7d-762238c11699.png)

**Comment by markherringer** [comment]
ok, this seems to have disappeared now
