### ISSUE TITLE
copy update on registration page

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#489]
http://healthsites.io/signin/

change..

Sign in
Please sign in with one of your existing third party accounts.

Important! If you already connected one 3rd party service, first login using that service and add more authorisation options on profile page

to

Sign in
Please sign in with one of your existing third party accounts.

Important! If you have already connected a 3rd party service, first login using that service and then add more authorisation options on profile page

**Comment by meomancer** [comment]
@markherringer already add to staging
