### ISSUE TITLE
country place name not working in place search

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#503]
As a user searching on place I expect to see the country view when typing in a country name.

Currently when a country name is placed in the 'place' search the search result is a 'no name healthsite'.
The search result should be a country view but without the polygon.
http://staging.healthsites.io/map?country=Sri%20Lanka

![sri-lanka](https://cloud.githubusercontent.com/assets/38838/12912519/cd901bf4-cf21-11e5-875e-49b852c429c3.png)

**Comment by meomancer** [comment]
![screenshot from 2016-02-10 07 40 30](https://cloud.githubusercontent.com/assets/4530905/12935650/080777de-cfca-11e5-9963-601a69928f76.png)

it is working from my side
what browser did you use, @markherringer ?
it seems that backend was failed giving polygon back then

**Comment by markherringer** [comment]
use the first option without the polygon
