### ISSUE TITLE
Error 404 page not found

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#520]
we need to a page not found message

==================================================

Error 404 - Page not found

We're sorry, but the requested page could not be found.

Go to homepage

===================================================

see :
http://www.sainsburyslivingarchive.co.uk/collections/world-war-i-centenary/our-royal-british-legion
http://www.sainsburyslivingarchive.co.uk/collections/world-war-i-centenary/our-royal-british-legi

**Comment by meomancer** [comment]
staging updated
page not found will be shown like this screenshot

![screenshot from 2016-03-23 12 27 52](https://cloud.githubusercontent.com/assets/4530905/13976496/e5f18168-f0f2-11e5-9951-b1b859ce3680.png)
