### ISSUE TITLE
after sign up return to map

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#550]
as a user I expect to return to the URL I was on before sign up

for instance:
https://healthsites.io/map#!/locality/287d50afa35742c3854babbb63f7912f

sign in using twitter

return to 

https://healthsites.io/map#!/locality/287d50afa35742c3854babbb63f7912f

when a user selects the sign-up link from the http://healthsites.io/map they should return there after successfull sign-in

**Comment by meomancer** [comment]
fixed on staging
