### ISSUE TITLE
percentage complete

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#599]
how should we present the % complete to the user?

Some healthsites will be able to tick/update all the attributes. Others will be complete with just a couple of core attributes ticked.

Maybe we should allow 100% completness once a validator has marked it so..?

https://github.com/healthsites/healthsites/wiki/Healthsite-attributes
https://github.com/healthsites/healthsites/wiki/context-of-the-healthsite

**Comment by meomancer** [comment]
hi @markherringer 
i don't understand how to be 100%
is it if all of mandatory and core is filled, it will be 100%?

**Comment by markherringer** [comment]
Hi @meomancer but what about the healthsites that do not have all the possible services available. They could be 100% accurate and complete with just a couple of attributes. Like a small clinic for instance that does not have a laboratory ect.

**Comment by meomancer** [comment]
@markherringer 
how do we know what is service available in a locality? how do we tell backend?
i think we need make document for this
and distict locality by type
and document for what services is available for it's type

**Comment by meomancer** [comment]
we could reopen in new ticket about method for percentage
