### ISSUE TITLE
we need a blog

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#620]
as a healthsites administrator I want to log into a blog and write articles for healthsites

explore django blogs

blogs.healthsites.io
https://www.djangopackages.com/grids/g/blogs/
http://pydanny.blogspot.co.uk/2009/04/show-me-your-open-source-django-blog.html
http://docs.getpelican.com/en/3.6.3/

**Comment by meomancer** [comment]
i think we can use http://mezzanine.jupo.org/docs/overview.html
it is still updated until now, the most downloaded package and also, it is almost like wordpress (already tried it)
