### ISSUE TITLE
Retrieve all the master records within a given geographical area

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#622]
Example: http://healthsites.io/api/v1/healthsites/search?search_type=placename&name=”Cape Town”

https://docs.google.com/document/d/1O0uWYTIWUMDJgERYBpU3GBFgMXNoFDakO_F-966qkGk/edit?usp=sharing

**Comment by meomancer** [comment]
waiting for masterisation (now is retrieve all record)

**Comment by markherringer** [comment]
@timlinux can you confirm that the user story is complete?

**Comment by meomancer** [comment]
v2 has changed and no masterization anymore
