### ISSUE TITLE
Retrieve all the master records within a given geographical area using search

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#623]
https://docs.google.com/document/d/1O0uWYTIWUMDJgERYBpU3GBFgMXNoFDakO_F-966qkGk/edit?usp=sharing

We need user stories:
As a XXX I need to XXXX so that I can XXXX

As a developer I need to Retrieve all the master records within a given geographical area using search so that I can show it on my own website

**Comment by meomancer** [comment]
waiting for masterisation (now is retrieve all record)

**Comment by meomancer** [comment]
v2 has changed and no masterization anymore
