### ISSUE TITLE
automatically mark a healthsite as a potential synonym

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#628]
as an administrator I expect the system to find healthsites that are potential synonyms and mark them as such

potential rules:
matching mandatory attributes
similar mandatory attributes

matching mandatory attributes
- uuid
- date-modified
- name
- geom
- source

https://github.com/healthsites/healthsites/wiki/Healthsite-attributes

Example location 
https://healthsites.io/map#!/locality/a270e62408e94cb2aaed0d5ffa32518a

As an administrator I need to see a list of potential synonyms so that I can manually establish a master.

**Comment by timlinux** [comment]
Also match spatial properties

**Comment by timlinux** [comment]
Note that spatial overlap is not necessarily an indicator of duplication

**Comment by markherringer** [comment]
![masterisation](https://cloud.githubusercontent.com/assets/38838/15113595/1d4d99c0-15ed-11e6-8412-c91edd549f13.png)

**Comment by meomancer** [comment]
currently we are using docker osm
which is will be reviewed by community for duplication
but we already has duplication system, so masterization is not needed
