### ISSUE TITLE
Add location to HS from external application

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#630]
Example end point: http://healthsites.io/api/v1/healthsites/add

As a user of Watchkeeper I would like to add a location to healthsites.io through the Watchkeeper application using the HS API

Normal course:
User logs into Watchkeeper and healthsites.io
User adds location to Watchkeeper
Watchkeeper posts location to healthsites.io

As a healthsites administrator receiving locations from external applications using the HS API I expect to see values for all mandatory attributes in the locations supplied.

https://github.com/healthsites/healthsites/wiki/Healthsite-attributes

**Comment by meomancer** [comment]
the url : https://staging.healthsites.io/api/v1/healthsites/facility/add

**Comment by meomancer** [comment]
our API docs https://healthsites.io/api/docs/
