### ISSUE TITLE
add new

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#633]
as a user I expect to see a new location marker on the map after signing in.

Normal course: 
User on map page is not signed in
Select +add new
user is requested to sign in
Select twitter ect 
User is re-directed back to map
User see's a marker on the map

**Comment by meomancer** [comment]
Already pushed to staging, as well as edit

**Comment by markherringer** [comment]
After signing in I am redirected to the world view of the map
I expect to return to the place on the map where I wanted to put the new location

Normal course: 
1) User on map page is not signed in
2) User finds new place on the map by zooming in, browsing the map
3) Select +add new
4) user is requested to sign in
5) Select twitter ect 
6) User is re-directed back to map < the user needs to returmn to the area on the map they found in step 2 above
7) User see's a marker on the map

**Comment by meomancer** [comment]
fixed on staging
