### ISSUE TITLE
return to url of shared healthsite

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#634]
as a user click a URL of a healthsite shared via social media I expect to return their after signing in.

Normal course for signed out user:
1) navigate to a healthsite
2) share site via social media 
3) open link shared in tweet, facebook, google + ect
https://healthsites.io/map#!/locality/c660d7e7b0a24e70b507b11049d78c6a
4) signin
5) ...at this point the user should be re-direct back to the link above

**Comment by meomancer** [comment]
fixed on staging
