### ISSUE TITLE
create json template file for healthsites

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#637]
as an administrator I need to be able to map CSV columns to the json file so that data is loaded to healthsites

**Comment by meomancer** [comment]
@markherringer 
[__template.zip](https://github.com/healthsites/healthsites/files/171638/__template.zip)
in this template, there is 2 file, which is json and csv. You could use json to upload it in data loader.
for making csv, you could try to use __template.

But, if you already has csv file, make sure the title of column is same in template.json 
For example:
```
"attributes": {
        "name": "Health Facility",
        "physical_address": "Address",
	"nature_of_facility":"Nature of Facility",
        "scope_of_service": "Scope of Services",
	"ancillary_services" : "Ancillary Services",
	"activities" : "Activities",
	"inpatient_service" : "Inpatient Services",
        "data_source": "Source of info",
	"ownership": "Ownership",
	"staff" : "Staff",
	"tags" : "Tags"
```
column of "Scope of Services" should be named "Scope of Services""

Here is corrected rwanda.csv. Just edited the title of column
[Rwanda.csv.zip](https://github.com/healthsites/healthsites/files/171641/Rwanda.csv.zip)
