### ISSUE TITLE
data loader security

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#650]
as an administrator I want to know that the HS list I agree with a trusted user will be loaded by them as agreed

Normal course:
User shares list with HS admin
HS administrator prepares list on Gdrive
HS administrator downloads LIST to Machine
....irwan complete here..

**Comment by meomancer** [comment]
pull : https://github.com/healthsites/healthsites/pull/667

**Comment by markherringer** [comment]
what is the process of establishing a trusted user?
