### ISSUE TITLE
view trusted user status

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#679]
As a user I want to be able to review another users status and see if they are trusted by healthsites.io or not.

If the user is trusted I expect to see a 'Trusted user' tag on the users profile.
In addition I expect to see which organisation the user is representing.

See attribute: source - Name and or website of the organisation supplying the data

https://github.com/healthsites/healthsites/wiki/Healthsite-attributes

**Comment by meomancer** [comment]
every user that login is using osm account
