### ISSUE TITLE
user name issue between social accounts

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#727]
as a user i want to be sure that when I sign in with my accoun t name in twitter another user with the same name in google will not be able to pose as me.

'Now there is no randomed user (i.e : sharehealthsitedat093738a). It is happened because the user with username sharehealthsitedata is already in db, and instead linked to sharehealthsitedat093738a, i link the social user to sharehealthsitedata'

do we want to be able to associate user accounts with a profile page

**Comment by meomancer** [comment]
Django social auth will create new account with randomize uuid, like "meomancer054030". 
- What i have don't, i am not sure, to prevent that number (check the username that provide from social account, if there is user with that username, link social account to clean one "meomancer", and delete "meomancer054030"). But the cons is : it will be linked with same user from different social auth with same username. It is risked
- What i did before this change. Just do what django social auth done, but save that username as "screen name". The cons : "the url will be /profile/meomancer054030, but the screen name in profile will be meomancer"
