### ISSUE TITLE
We need off-host backups

### ISSUE THREAD

**Issue by timlinux** [healthsites/healthsites#739]
Currently we make nightly backups to  `/home/web/healthsites/deployment/backups/` but the backups reside on the server. When we purchased server space from hetzner we also bought sftp storage for offsite. We should add to the cron job a task to copy these backups offsite.

@markherringer please provide me with the sftp connection details for our offsite storage and I will set this up.

**Comment by meomancer** [comment]
we are using osm, so it is our backups data
but for our django data (the non osm data) we still need backups
