### ISSUE TITLE
change the name attribute to mandatory

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#742]
as a developer I expect to see the name attribute in the mandatory attribute list

Please could we discuss how best to do this.

{
     "geom": [5.09010985, 13.04530082], 
     "version": 1, 
     "values": {
          "physical_address": "Wamakko", 
          "data_source": "http://nmis.mdgs.gov.ng/", 
          "type": "Dispensary", 
          "name": "Boyen Dutse Dispensary"
    }, 
    "uuid": "f99ddf7c95404bfaa95b2445438a4c46", 
    "changeset": 51313
}

https://github.com/healthsites/healthsites/wiki/Healthsite-attributes

**Comment by meomancer** [comment]
the data is not relevant
