### ISSUE TITLE
Raw Data link missing

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#743]
Currently our production server is using the data that was in place on staging.
Staging had received list uploads from:
* data.gov.uk, 
* standbytaskforce, 
* health-ministry-of -kenya, 
* health-ministry-of -rwanda, 
* nigeria MDG infomation system, 
* kenya open data, 
* testismail600

example:
https://www.healthsites.io/map#!/locality/f2adb2ed36e748879ee3ee293d4e0597
https://staging.healthsites.io/map#!/locality/f2adb2ed36e748879ee3ee293d4e0597

**Comment by meomancer** [comment]
For production i found that incorrect localities (not OSM, and don't have raw link except the locality that created by user) are around 42992 localities

**Comment by markherringer** [comment]
Hi @meomancer @timlinux yes, we need to re-load these locations. I will list the upload files here:
Nigeria:
https://docs.google.com/spreadsheets/d/1ddTv1D39ab1QymQ9ZN8MFpgmXKTRRmDdPvMJ_Ue3HXQ/edit?usp=sharing
