### ISSUE TITLE
updated OSM import

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#754]
as a user I want to see an updated list of OSM locations in the site so that I know I am seeing the most up to date information

Next step:
establish a cron job for the OSM import
- get the scripts merged into Git for the Healthsites.io web site
- get the scripts running nightly on a cron
- do this first on the staging server, then deploy to live once you, Irwan and Mark are happy that it is working.

Questions:
How do we avoid duplicates?
How do we import amended attributes?

@meomancer please could you list the sources of data we currently have.
we need to ensure that the raw data link either links to a .csv file on HDX or OSM

**Comment by meomancer** [comment]
@markherringer for raw source, what we have now is just HDX (that MSF data we uploaded) and OSM
The others doesn't have raw source

**Comment by markherringer** [comment]
#846

**Comment by timlinux** [comment]
@meomancer and @Gustry Could you guys help to get the automated import via cron set up please?

**Comment by meomancer** [comment]
we are using docker osm now
