### ISSUE TITLE
Unique Property Reference Number

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#757]
as a healthsites admin I want to link the unique ID of a healthsites location to the UPRN

https://www.gov.uk/government/speeches/geoplace-conference-matt-hancock-speech

The Unique Property Reference Number (UPRN) is the unique identifier for every addressable location in Great Britain. - See more at: https://www.geoplace.co.uk/addresses/uprn#sthash.HDehk02I.dpuf

**Comment by meomancer** [comment]
we are using osm data and we already have uuid
