### ISSUE TITLE
nigeria locations

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#781]
locations are not displaying accurately

search on BERACAH CLINIC

we need to check the data on HDX

**Comment by markherringer** [comment]
![image](https://cloud.githubusercontent.com/assets/38838/15447071/e03f09ea-1f2b-11e6-995d-8678f2869ca6.png)

![image](https://cloud.githubusercontent.com/assets/38838/15447075/0a38f5b2-1f2c-11e6-91d5-7be8a111492d.png)

**Comment by meomancer** [comment]
data is not good
