### ISSUE TITLE
missing options in form?

### ISSUE THREAD

**Issue by mmoreno-cart** [healthsites/healthsites#788]
Sorry if this has been already discussed.

I see in the form (edit healthsite) a couple of multiple choice fields where some options could be missing, taking the [attribute wiki](https://github.com/healthsites/healthsites/wiki/Healthsite-attributes) as reference.
- ancillary-services: "Emergency department" missing
- activities: "mental health", "geriatric care" and "social care" missing

**Comment by meomancer** [comment]
The data has been changed
