### ISSUE TITLE
We need to supply shape dumps

### ISSUE THREAD

**Issue by timlinux** [healthsites/healthsites#795]
In our original vision we would make the entire dataset available easily for bulk downloads as shape files, css, excel, xml etc. Lets start with shapefile and the others can easily follow:

- [ ] Write a view for postgres that includes the geometry, geometry x and y as text, mandatory fields as location and all core fields. Discuss with Mark if we want to include other fields too.
- [ ] Write a cron job that does a nightly pgsql2shp dump of the data into a download directory. I do not propose to keep archives at this stage so I suggest to always replace the old extract when the new one is ready
- [ ] Update the 'get the data' section on the landing page to include a link to download the latest shp. Design it so that we can easily add other formats there in the future. We can convert to various formats using ogr2ogr so this should be trivial.

**Comment by markherringer** [comment]
shapefile is missing a projection file

**Comment by markherringer** [comment]
when opening Venezuela.dbf    I get 'General Error. General input/output error'
