### ISSUE TITLE
oauth

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#804]
as a user I want to sign in with my social media account so that I can access healthsites easily

osm - 
Github - 
linkedin - 
google - 
twitter - done
facebook - done

during the sign on process I expect to be informed of the data healthsites will use from my account and how I can manage it.

**Comment by dodobas** [comment]
so we are missing support for osm, linkedin and google oauth providers? and we should enable those?

**Comment by markherringer** [comment]
We need to review how we want this process to work...

The OSM account will be the primary account.
It will will allow the user to write directly to OSM once #888 and #889 have been developed.

The idea of having the Twitter, Facebook and Linkedin accounts available achieve the following two objectives:
1) Easy authentication
2) Opportunities to share Healthsite locations into Social networks and request validations

They should be seen as secondary to the OSM account.

From the profile page, established following the initial registration, the user can choose to add additional profiles to the account.
https://healthsites.io/profile/sharehealthdata/

When a user wants to share a healthsite with Twitter/Facebook/Linkedin the system should detect which authentication method is active and either proceed or redirect back to profile/page and request activation.
