### ISSUE TITLE
materisation copy update

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#815]
This is a **potential master** for:
- Heart Hospital under construction 2015
- Tim hospital

This is a **potential alias** for:
- Foo hospital
- Bar hostpital

This is the **confirmed master**for these aliases:
- XYZ Hospital
- JJJ Hospital

This is a **confirmed alias** for this master:
- HHH hospital

**Comment by timlinux** [comment]
A couple of notes:

* There may be zero or more potential masters for any given record
* There may be zero or more potential aliases for any given record
* A confirmed master may have zero or more confirmed aliases
* A confirmed alias can only ever have one confirmed master

**Comment by meomancer** [comment]
Masterization is not in v2
