### ISSUE TITLE
update data model diagram

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#820]
https://docs.google.com/spreadsheets/d/1FlQZUC1GtH00AmyFixweB9vQnoPB9a7LYASCRnEvNBU/edit?usp=sharing

![healthsites-data-model](https://cloud.githubusercontent.com/assets/38838/16224953/4436961a-379c-11e6-9754-c53686dc2981.png)

**Comment by meomancer** [comment]
New model diagram
![healthsite model diagram - standard](https://cloud.githubusercontent.com/assets/4530905/16861059/8c021162-4a67-11e6-9e0f-a4016ce35bff.jpeg)
