### ISSUE TITLE
change amended to added

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#821]
change
21 June 2016 10:21:37 - @sharehealthdata - 1636 HS/amended

to

21 June 2016 10:21:37 - @sharehealthdata - 1636 HS/added

**Comment by meomancer** [comment]
@markherringer 
it is occured because system doesn't saved state when version 1
i am sorry, that i accidently remove the code. It is for data from May.
already fix it, but for current data, "added" will not be shown in updates
