### ISSUE TITLE
publish text when no link to data supplied by available

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#831]
as an administrator I expect the 'Source of info name' to be published without a link when their is no 'Source of info URL' available so that I know where the data comes from.

https://healthsites.io/map#!/locality/5443c898e4f24f54866c5c38f4685da9

**Comment by meomancer** [comment]
source has different method
it is not saved in locality, but domain is saved in Sites table : https://healthsites.io/admin/sites/site/
when first upload csv, it will save Source of info name to locality and Source of info name & Source of info URL to sites
so, if the sites will be saved although it is wrong and updated in next uploads

for this, we could just delete on above url and it is independent with locality

*note*: production's sites is cleaned
