### ISSUE TITLE
need to download data from venezuela , how I can do that ?

### ISSUE THREAD

**Issue by juliocastrom** [healthsites/healthsites#842]
Hi Julio, thanks for the message. We are currently developing this feature. If you have questions please join us here https://gitter.im/healthsites/healthsites

Here is a link to the data for Venezuela: 
https://staging.healthsites.io/map?country=Venezuela

**Comment by meomancer** [comment]
@juliocastrom 
currently we provide shapefile on country page
please check in here : https://healthsites.io/map?country=Venezuela
