### ISSUE TITLE
New OSM data import

### ISSUE THREAD

**Issue by Gustry** [healthsites/healthsites#846]
- Run the extract script from OSM to get every hospitals/clinics.
- See how many new objects are in the list using the OSM provider in healthsites.io (newly created objects since december 2015)
- See how many of the new objects have exactly the same lat/long as objects in healthsites.io using every providers except OSM in healthsites

**Comment by smit1678** [comment]
@Gustry One discussion point on the first item for getting OSM features (moving from email chatter): 

Suggestions on how we expand what we pull into Healthsites? Should we make a list of the tags that we want to pull beyond `amenity=hospital` and `amenity=clinic`? 

Some features do not have the current tagging method of `amenity=*`. There are cases where a building (or set of buildings) is tagged as `building=hospital`. We don't want to pull in `building=part`, only the area that covers the hospital grounds, i.e. http://www.openstreetmap.org/way/342749503. Goal here is that we don't just pull in what is rendered on the map, but we pull in all related data to improve and contribute back to OSM. 

Another example is the features that use the newer [Healthcare 2.0 tagging method](http://wiki.openstreetmap.org/wiki/Proposed_features/Healthcare_2.0): https://www.openstreetmap.org/way/78056419.

**Comment by meomancer** [comment]
we are using docker osm
