### ISSUE TITLE
Expanding the Type attribute

### ISSUE THREAD

**Issue by smit1678** [healthsites/healthsites#847]
Right now we're only tracking three facility types: 
1. Hospital
2. Medical clinic
3. Orthopaedic clinics

This is a pretty limited categorization to capture the wide range of terminology and types that are seen around the world. We also have zero facilities categorized as `orthopaedic clinics`. While it may be helpful to take a standardized view for the Healthsites frontend, we should still keep the original categories if available and provide a flexible way to track this. 

Proposing the following way to expand beyond the three categories for the frontend: 
1. Hospital (Higher-level, provincial/referral/large)
2. Hospital (Lower-level, district/subdistrict/small)
3. Health centres
4. Dispensaries and Medical Clinics 
5. Other

One of the goals here is to start to capture the difference between levels a bit more. Knowing if a facility is tagged as a Health Centre (in some countries this helps show that the facility has a diagnostic capacity) as opposed to a dispensary or clinic (no diagnostic capacity). 

Questions to continue the discussion: 
- @markherringer @rsaameli What was the original purpose of including Orthopaedic clinics as a specific separate category?

**Comment by markherringer** [comment]
Agree @smit1678 The initial focus following recommendations from Eric de Roodenbeke and the IFH was to just focus on these three. Lets do as suggested and save the proposed facility types, present to gov team, and then potentially publish

**Comment by rsaameli** [comment]
i agree refining the datamodel is very tempting but here  'Less is more' really applies.
What are the proposed thresholds between the classes ? Even WHO does not come up with clear rules and leaves it up to countires to decide. [http://www.who.int/entity/healthinfo/systems/WHO_CreatingMFL_draft.pdf?ua=1](url)
I'm not opposed but we take the risk of opening up Pandoara's box ...
 
As for Orthpaoedic centres we would have a round 600 to add but it is true that this on is not a 'must have' so if we want to xpand the Hospital types, we could remove Orth centre to compensate.

**Comment by rsaameli** [comment]
fyi, here are the classes that ICRC Health unit decided to settle for internally as par of an internal revision (Recipient Places) : 
![mwsnap006 23-08-2016 18_09](https://cloud.githubusercontent.com/assets/8932954/17899812/df47efb8-695c-11e6-8835-920befe761a3.png)

**Comment by smit1678** [comment]
@rsaameli Thanks for sharing the image and the input. I'm not sure how a first aid post is defined (is this a temporary facility?). Based on this feedback, it sounds like a simpler but expanded list that captures first aid posts and rehab centres could then be: 

1. Hospital
2. Health centres
3. Dispensaries and Medical Clinics
4. Other

These names don't necessarily need to be used, but I think there it would be useful to distinguish between larger inpatient capacity, diagnostic capacity, and outpatient only capacity. And these general categories could capture that. 

Agreed on the point for leaving up to countries. We may want to make sure we keep track of this original facility type category since it'll be useful within the country it is location. As I mentioned earlier, this would be for a global or regional usage (and the frontend of healthsites).  A generalized and standardized recategorization can be used for comparison across countries.

**Comment by meomancer** [comment]
currently we are using osm list
