### ISSUE TITLE
MEDIA_ROOT en STATIC_ROOT should be overriden in dev

### ISSUE THREAD

**Issue by milovanderlinden** [healthsites/healthsites#855]
By adding:

```
STATIC_ROOT = '/home/web/static'
MEDIA_ROOT = '/home/web/media'
```

to `django_project/core/settings/dev_dodobas.py` and writing a clear instruction in `README.md` this installation issue can be prevented. For my personal setup, I have changed them to:

```
STATIC_ROOT = '../deployment/static'
MEDIA_ROOT = '../deployment/media'
```

**Comment by dodobas** [comment]
this was fixed, https://github.com/healthsites/healthsites/blob/master/django_project/core/settings/base.py#L48
