### ISSUE TITLE
Robust OSM query

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#856]
As an administrator I want to make a robust query of OSM so that I import healthsites that have different tag/attribute structures:
*tagged as building=hospital
*tagged amenity=hospital or amenity=clinic.

Actually there are 38,000 buildings tagged this way in OSM: http://taginfo.openstreetmap.org/tags/building=hospital#map. 

We need to think through the tags we’re importing beyond just amenity=*.

**Comment by Gustry** [comment]
In my opinion, as an OSM contributor, we shouldn't import building=hospital into HS.
* If the hospital is only one building, the way must have : 
  * `amenity = hospital` AND `building=hospital`
* If the hospital is composed of many buildings : 
  * on each building : `building = hospital` only.
  * on a bigger polygon containing every buildings : `amenity = hospital`.

According to the [wiki building=hospital](http://wiki.openstreetmap.org/wiki/Tag:building%3Dhospital):
> A building which forms part of a hospital. Use amenity=hospital for the hospital grounds.

If you found some mistakes in OSM like an hospital described as only `building=hospital`, maybe we should write a rule into a Quality Assurance tool such as [osmose](http://osmose.openstreetmap.fr) to raise an issue if a building=hospital is not tagged as amenity=hospital OR is not included in a bigger polygon amenity=hospital.

**Comment by markherringer** [comment]
Hi @Gustry . Yes, I like this suggestion to create a Quality Assurance tool. 
I understand that if the hospital is **just one** building then :
*amenity = hospital **AND** building=hospital

If the hospital is composed of **many** buildings then:
*on each building that is a hospital place : building = hospital
*on the polygon that defines the area of the hospital place : amenity = hospital

Questions:
What happens when the hospital is spread out and cannot fit into one polygon.
Do we assign the same hospital name to each polygon  associated with the hospital in question?



This tool could invite users to identify the polygon of the hospital and or define the

**Comment by smit1678** [comment]
To add here, some of this discussion also happened in #846 which also pulls in the Healthcare 2.0 tagging model. I agree with @Gustry that it's probably best to move to do a clean up of existing health facilities in OSM to get their tagging schema in line with expected and have a simple query we use to sync with Healthsites. We can then have a QA method for bringing new facilities that are added directly into OSM that don't follow the tagging model. I think Healthsites could help coordinate that.

**Comment by Gustry** [comment]
There is one principle in OSM : One feature, one OSM element
http://wiki.openstreetmap.org/wiki/One_feature,_one_OSM_element

If the hospital is spread out and cannot fit into one polygon, you have to use a OSM Relation multipolygon : http://wiki.openstreetmap.org/wiki/Relation:multipolygon with many "outer" rings. These objects have already been imported into HS.

Some existing QA tools on OSM : http://wiki.openstreetmap.org/wiki/Quality_assurance
I was speaking about Osmose.

**Comment by markherringer** [comment]
@Gustry @smit1678 here is an example of where..
.. the hospital is composed of many buildings then:
*on each building that is a hospital place : building = hospital
*on the polygon that defines the area of the hospital place : amenity = hospital

https://healthsites.io/map#!/locality/1657eba8d9b94ddcbeb80d886a1e8c4a
https://www.google.co.uk/maps/place/Hospital+De+Gisenyi/@-1.7029982,29.2607436,17.58z/data=!4m5!3m4!1s0x0:0x7a4e0242b276d3a4!8m2!3d-1.7008929!4d29.2625248

**Comment by markherringer** [comment]
The locations loaded by the American Red Cross need to be imported into healthsites.io
https://data.humdata.org/dataset/american-red-cross-west-africa-project

Currently these facilities are not appearing . to test search on ..Esther Y.Barkolleh

**Comment by Gustry** [comment]
One missing clinic in HS : http://www.openstreetmap.org/node/4131217597 ?

**Comment by meomancer** [comment]
we are using docker osm
