### ISSUE TITLE
Remove Orthopedic clinic from graph

### ISSUE THREAD

**Issue by smit1678** [healthsites/healthsites#858]
There are zero facilities being tracked as orthopedic clinic. Let's drop this from the graph to simplify the Type breakdown. Currently this is a bit confusing when showing zero. 

![healthsites io 2016-10-12 10-39-01](https://cloud.githubusercontent.com/assets/796838/19305283/19f840ae-9068-11e6-9b67-e03451486eb1.png)

Related to #847

**Comment by meomancer** [comment]
we are using type list from osm
