### ISSUE TITLE
Rwandan healthsite coming up in Burundi shape file

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#863]
Search on Kigembe CS

http://staging.healthsites.io/map#!/locality/556cd00467be49209a9552afc09982d3

![image](https://cloud.githubusercontent.com/assets/38838/19520257/82baf7e0-9607-11e6-8557-85317e1cd45e.png)

**Comment by Gustry** [comment]
Someone raised maybe the same issue in France.
If you go in Saint-Pierre, La Réunion, the mask layer is very simplified and HS is missing statistics about this city.

See my screenshot about Saint-Pierre : 
<img width="833" alt="screen shot 2016-10-19 at 21 49 26" src="https://cloud.githubusercontent.com/assets/1609292/19523902/29b3951e-9646-11e6-8173-d8967208268d.png">

**Comment by meomancer** [comment]
we are using docker osm
