### ISSUE TITLE
https issue

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#864]
https://staging.healthsites.io/ is down but http://staging.healthsites.io/ works.

Is this a 'let's encrypt' issue or maybe the DNS management?

**Comment by smit1678** [comment]
@cchristelis Is this the same issue as we had with the TLD? I see we're using Cloudflare, but are we using their Flexible SSL or Full SSL method?

**Comment by dodobas** [comment]
this seems to be resolved, not sure what was the original problem
