### ISSUE TITLE
push to OSM

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#869]
As a healthsite administrator I want to push HS locations to OSM so that HS data is available via openstreetmap.org

**Comment by smit1678** [comment]
An MVP approach may be to export updates as a list, and then integrate the changes into OSM in a semi-automated way using existing OSM editing tools like http://maproulette.org/ or https://osmlab.github.io/to-fix/. We can leverage the community to help make the changes in to-fix or maproulette. 

An alternative (and would require a restructure) would be to change the model to be directly editing OSM using your OSM username -- more in line like https://www.mapcontrib.xyz/ or https://wheelmap.org.

**Comment by meomancer** [comment]
v2 make it works
