### ISSUE TITLE
Masterisation backlog

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#872]
as a user I would like to see a backlog of masterisation tasks so that I can find one that I can do.

This call to action invites the user to find and review potential masterisation opportunities.
The masterisation opportunities are presented in the same way that healthsites are [presented.](https://github.com/healthsites/healthsites/issues/873)
To perform a masterisation update the user registers and makes [request](https://github.com/healthsites/healthsites/issues/874) for a trusted user status.

**Comment by meomancer** [comment]
we are not using masterization anymore
