### ISSUE TITLE
We need to handle a use case when a single user authenticates on multiple services

### ISSUE THREAD

**Issue by dodobas** [healthsites/healthsites#88]
For example a user might have different social accounts on different services. At the moment if a user tries to 'connect' Multiple Social accounts but uses the same account we get an `AuthAlreadyAssociated` exception. 
- login using OSM
- logout
- login using Twitter
- go to profile, click on OSM (auth)
- FAILS with AuthAlreadyAssociated  as a user with that specific OSM account already exists

**Comment by meomancer** [comment]
we just using osm auth now, so this will not be the case
