### ISSUE TITLE
write to OSM

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#888]
as a user I want to update healthsite.io attributes directly to OSM so that the data is available to others via openstreetmap

https://docs.google.com/spreadsheets/d/1ycaqJH-GHHs-Z5wyNpRaWOh8HWCZpSz_K-nz5a34imw/edit?usp=sharing

Notes:
Currently healthsites.io saves to a postgres database. We want to use openstreetmap as the database and postgress as a caching service to present qualitative analysis

**Comment by meomancer** [comment]
v2 make it true
