### ISSUE TITLE
the shp download is always stopping

### ISSUE THREAD

**Issue by yrebois** [healthsites/healthsites#893]
Hi we are consuming ona daily basis the shp from here https://healthsites.io/media/shapefiles/facilities_shapefile.zip we realize
that the size is 2.5 GO for 189007  points. it is a bit too big  nope? 
it is stopping from all browsers and as well from our FME connector. when we try to synchronize with your remote shp.

Any problems  from your side ?
any alternative (JSON) ?   

Thank you for the quick fix !

sincerly 
Yann , from ICRC

![Uploading ScreenHunter_1855 Feb. 24 14.44.jpg…]()

**Comment by meomancer** [comment]
hi @yrebois 

i think for getting data with shapefile is quite not good, because our shape file is big (because of a lot of location and location's attributes)
i prefer to use JSON with pagination:

here is the API for this:
https://github.com/healthsites/healthsites/wiki/API#11-getting-all-facilities

Thank you

**Comment by yrebois** [comment]
Hello 
 I am surprise by the size of your shp,  189007 points with few attributes ... for 2.5 GO?  mm it is weird ! was not the case some months ago. 
working with a Shp is convenient offline and with a regional approach without to download country by country .
We had some process and some ETL already put in place .for the ICRC we will have to adapt our process ! (we are working with FME to get the data.
if we work with your API(to get the whole data or  most recent one , do you have a notion of count of objects ?  like http://acleddata.com/api/acled/read   yours is 100  

    page - each page contains maximum 100 healthsites

what should we do if we want to have one  full datatset  ?

sincerly
Yann , from ICRC

**Comment by markherringer** [comment]
'I realized that the *.shp is increasing every day.. as today we are at 2.9 GO ..'

**Comment by Gustry** [comment]
And tonight it's 4.11 go. Something is wrong. A shapfile wih 189007 points can't be more that a few hundreds mega I think. I didn't look to the attribute table.
@meomancer Can you tell use in the code where is shapefile is generated ?
Is-it generated on the fly ? Or is it a process every night ?

**Comment by meomancer** [comment]
hi @Gustry 
it is every night and generated on fly
it seems that the file was corrupted. I'm checking what is the problem

@markherringer @yrebois 
file now just 638MB, but i'm still checking why the file was so big

**Comment by yrebois** [comment]
working again! txs
Y

**Comment by Gustry** [comment]
I will keep this issue open. We need to fix this.

**Comment by Gustry** [comment]
> file now just 638MB, but i'm still checking why the file was so big

This was 5 hours ago.
It's 668,5 Mo just now.

**Comment by timlinux** [comment]
Even 638MB seems rather large for 180k points.....

**Comment by Gustry** [comment]
3.6 go this morning again.
We need to fix this asap
