### ISSUE TITLE
include size of file in shape file download sentance

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#896]
Change..
You can get all data from healthsite in this shapefile

to..

Download all healthsite data in this shapefile (2.5 GB)

**Comment by yrebois** [comment]
hello today it is  3,8... 

![screenhunter_1902 mar 08 12 22](https://cloud.githubusercontent.com/assets/5664189/23702056/ee8b98e8-03f9-11e7-8ac0-0dfb87e1ae00.jpg)
