### ISSUE TITLE
Update the publication of  ODbL license

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#898]
This {DATA(BASE)-NAME} is made available under the Open Database License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in individual contents of the database are licensed under the Database Contents License: http://opendatacommons.org/licenses/dbcl/1.0/

https://opendatacommons.org/guide/
https://github.com/healthsites/healthsites/wiki/Data

**Comment by dodobas** [comment]
i'm not sure what to do here? what is expected?

**Comment by meomancer** [comment]
fixed by https://github.com/healthsites/healthsites/pull/1428
