### ISSUE TITLE
GeoJSON output invalid in staging

### ISSUE THREAD

**Issue by dickoa** [healthsites/healthsites#907]
Hi everyone,

Thanks again for this wonderful project, I work with the HDX team in Dakar.
I was playing with staging to get the new pagination feature for country (i.e get all health sites from a country using the search api) but I found that when you want to get a facility details through the api (using uuid), the GeoJSON output is different if I use the production instance or staging. The staging one being not valid.
Using the example from the wiki, we have:

```
https://healthsites.io/api/v1/healthsites/facility/details?uuid=47d5bd1449d143c99b9ba0042d31cfdd&format=geojson
```

```
{"type": "FeatureCollection", "features": [{"geometry": {"type": "Point", "coordinates": [-109.420938926046, -27.1505165]}, "type": "Feature", "properties": {"raw-source": "http://www.openstreetmap.org/way/379766394", "source_url": "https://www.openstreetmap.org/", "what3words": "cloudless.vocalists.hardbacks", "upstream": "openstreetmap\u00b6w379766394", "name": "Hospital de Hanga Roa", "completeness": "35.29%", "uuid": "47d5bd1449d143c99b9ba0042d31cfdd", "date_modified": "2015-12-11T10:51:22.924Z", "source": "OpenStreetMap", "version": 2, "type": "hospital"}}]}
```

```
https://staging.healthsites.io/api/v1/healthsites/facility/details?uuid=47d5bd1449d143c99b9ba0042d31cfdd&format=geojson
```

```
{"type": "FeatureCollection", "features": {"geometry": {"type": "Point", "coordinates": [-109.420938926046, -27.1505165]}, "type": "Feature", "properties": {"raw-source": "http://www.openstreetmap.org/way/379766394", "source_url": "https://www.openstreetmap.org/", "what3words": "cloudless.vocalists.hardbacks", "upstream": "openstreetmap\u00b6w379766394", "name": "Hospital de Hanga Roa", "completeness": "35.29%", "uuid": "47d5bd1449d143c99b9ba0042d31cfdd", "date_modified": "2015-12-11T10:51:22.924Z", "source": "OpenStreetMap", "version": 2, "type": "hospital"}}}
```
In this case, the GeoJSON is not valid (using GDAL and GeoJSON lint)

I hope it helps and I am not sure if if an issue on the staging instance is useful since it's a work in progress. Let me know if you prefer that next time, I wait until you push it into production first.

Best,

**Comment by meomancer** [comment]
hi @dickoa 
they may be have different data because they use docker osm
maybe the staging was outdated (the docker osm was down) and still using old data
