### ISSUE TITLE
unique ID of healthsite from data source

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#911]
as a user I expect to be able to link the unique ID of the healthsite from a data source (openstreetmap, Ministry of Health ect) with the unique ID of https://healthsites.io

Currently we reference the source, in this case openstreetmap, where do we save the unque ID of the source data?
So in the case of 'Esther Y.Barkolleh'
https://healthsites.io/map#!/locality/21f43fc51a544352bb267394fb98d1fb

where is the unique ID?

http://www.openstreetmap.org/node/4131217597

**Comment by Gustry** [comment]
When it's a feature from OSM, there is usually a link 'Raw data' like on this one : https://healthsites.io/map#!/locality/ae8cf5d9028e4fabad806649358f36fd

I don't know why the `Raw link` is missing on yours Mark. The upstream id is there in the database:
https://healthsites.io/admin/localities/locality/334758/?_changelist_filters=q%3D21f43fc51a544352bb267394fb98d1fb

@meomancer Can you have a look to this issue? Thanks
