### ISSUE TITLE
Error 502 for Nigeria and Mali

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#916]
I have noticed that for nigeria & mali this query e.g https://healthsites.io/api/v1/healthsites/search?search_type=placename&format=csv&name=nigeria
more often returns a 502 error
I have also tried with the iso3 in place of the whole country name and get results ( excepts for nigeria and mali ).

**Comment by ndongamadu** [comment]
The right url is (note the format=geojson) : https://healthsites.io/api/v1/healthsites/search?search_type=placename&format=geojson&name=nigeria

It has returned results for the 2 countries one time, after that nothing but bad gateway Error 502.

**Comment by meomancer** [comment]
fix by : https://github.com/healthsites/healthsites/releases/tag/version-1_9_5
