### ISSUE TITLE
social_users - refactor models

### ISSUE THREAD

**Issue by dodobas** [healthsites/healthsites#943]
* instead of signals use simple procedural code
* move utility methods out of models into `utils.py`, keep models thin
  * like `Organisation.clean_website`
* add tests for the refactored/new code

**Comment by LeMeteore** [comment]
Hey o/

What do you think about? Also, in this model, I don't see any utility methods to move :\ 

```python
39 class TrustedUser(models.Model):
40     """                                                                                                                  
41     Extention of User                                                                                                    
42     """
43 
44     user = models.OneToOneField(
45         User, default=1, unique=True)
46     organisations_supported = models.ManyToManyField(
47         'Organisation', through=Organisation.trusted_users.through, blank=True
48     )
49 
50     def delete(self, *args, **kwargs):
51         DataLoaderPermission.objects.filter(uploader=self.user).delete()
52         super(TrustedUser, self).delete(*args, **kwargs)      
```

Now, my only concern is [this](https://docs.djangoproject.com/en/dev/topics/db/models/#overriding-predefined-model-methods):

> Overriding Delete Note that the delete() method for an object is not necessarily called when deleting objects in bulk using a QuerySet. To ensure customized delete logic gets executed, you can use pre_delete and/or post_delete signals.

Thanks a lot for the suggestions.

**Comment by meomancer** [comment]
we are just using osm account now
