### ISSUE TITLE
update healthsite attributes

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#944]
as a healthsite administrator I want to publish the most relevant healthsite attributes so that i can create an effective and useful baseline for healthsite stakeholders

## OSM mapping
https://docs.google.com/spreadsheets/d/1ycaqJH-GHHs-Z5wyNpRaWOh8HWCZpSz_K-nz5a34imw/edit?usp=sharing

## WIKI pages
https://github.com/healthsites/healthsites/wiki/Healthsites-data-model
https://github.com/healthsites/healthsites/wiki/Healthsite-attributes

## Healthsites blog
https://medium.com/healthsites-io/healthsites-io-attribute-definition-7feab3b78e6a

**Comment by meomancer** [comment]
we are using latest tags
