### ISSUE TITLE
upload bug

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#948]
the uploader successfully receives the file but does not load the data.

{
"message": "You have successfully upload your data",
"detailed_message": "Please wait several minutes for Healthsites to load your data. We will send you an email if we have finished loading the data.",
"success": true
}

We need to know where the issue is so we can identify and fix the errors in the upload files.

https://staging.healthsites.io/

CSV file
https://docs.google.com/spreadsheets/d/1pRQPWR8s2fsJ5LPfebha1Nal6xnLwIOYVWVuXsrMr5A/edit?usp=sharing

JSON file
https://drive.google.com/drive/folders/0B5CAbAqCEH-VZTl5MGs0UGRYckU?usp=sharing

**Comment by meomancer** [comment]
could you retest it with new form @markherringer ?

**Comment by meomancer** [comment]
This ticket is already out of date, because the form has changed
We can open new ticket if the bug is still occured
