### ISSUE TITLE
Healthsite name in English

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#953]
As a user I would like to see the Healthsite name in the local language and English so that I can correlate with other data sets.

Osm has the English and local name. We need to pull them both in.

'What we would need as cartographer user is to have one more column than what healthsites delivers now with the "english name". So that we can use it easily.'
![osm_english_name](https://user-images.githubusercontent.com/38838/28458341-b3fc1eee-6e09-11e7-97b5-f5da01952dbe.PNG)

**Comment by meomancer** [comment]
name is come from osm now
for language, it will cover by this ticket : https://github.com/healthsites/healthsites/issues/1388
