### ISSUE TITLE
link blog to healthsites.io navigation

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#954]
Add the blog to the navigation of https://healthsites.io/

[ Blog](https://medium.com/healthsites-io) -About -Map -Country data - How it works- Share data- Partners

**Comment by ericboucher** [comment]
@markherringer - I created PR #1039, note that this will redirect visitors to Medium and out of the website. Alternatively we can open a new window or tab with the blog post when visitors click on the "Blog" button.

**Comment by markherringer** [comment]
@ericboucher good call. open a new window
