### ISSUE TITLE
update strapline

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#956]
https://healthsites.io/

Change..

Building a free, curated, canonical source of healthcare location data

to

Building an open data commons of health facility data with OpenStreetMap

**Comment by ericboucher** [comment]
@markherringer I started a PR here https://github.com/healthsites/healthsites/pull/1038 but there are a few variation of these sentences such as "A free, curated, global, canonical source of healthcare location data" and others that you might want to tweak as well.

What is it that you would like to convey?

**Comment by markherringer** [comment]
Thanks @ericboucher 

'Building an open data commons of health facility data with OpenStreetMap'
