### ISSUE TITLE
update Number of heathsites per type to support other languages and types

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#966]
as an administrator I want to see the healthsite types correctly reflected 

![healthsites-types](https://user-images.githubusercontent.com/38838/36210561-005e1600-119f-11e8-88cc-b96bab7b1aac.png)

Poste de Santé
Unite de vaccination de l'HPD
Centre de Santé
CLINIQUE ASBEF
Hopital
Maternite

**Comment by meomancer** [comment]
Currently all healthsites per type is based on osm type list (just english language)
so it will reflect types of all data

to reflect user language, we can cover it using https://github.com/healthsites/healthsites/issues/1436
