### ISSUE TITLE
facebook login not working

### ISSUE THREAD

**Issue by markherringer** [healthsites/healthsites#967]
https://88.99.148.103/signin/

Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.

**Comment by dodobas** [comment]
this is fixed by updating the service server name to http://demo.healthsites.io

**Comment by markherringer** [comment]
new users can login but not existing users

**Comment by meomancer** [comment]
we are just using osm account now (because we are add/edit through osm)
