### ISSUE TITLE
Kartoza Epic 1: Write records directly to OSM on insert / update / delete

### ISSUE THREAD

**Issue by AlwynSmit** [healthsites/healthsites#992]
Kartoza Epic 1: Write records directly to OSM on insert / update / delete

**Comment by AlwynSmit** [comment]
Kartoza Epic 1: Write records directly to OSM on insert / update / delete

**Comment by timlinux** [comment]
I think for now we should not do delete operations. Lets constrain our work to update and insert operations.

**Comment by meomancer** [comment]
Everything is working fine
