### ISSUE TITLE
Kartoza Epic 1: User Story 1: Create new record

### ISSUE THREAD

**Issue by AlwynSmit** [healthsites/healthsites#993]
# Expectation
As an HS.io logged in user, when I create a new record in the user interface, I want to see that record appear in osm.org after a short interval.

# Acceptance criteria
Given that the HS.io UI is verified through unit testing to meet the specified requirements, when a user inserts a new record in HS.IO then this record shall appear in OSM and be retrievable via overpass.

child of #992

**Comment by meomancer** [comment]
Fixed by : https://github.com/healthsites/healthsites/issues/1099
