### ISSUE TITLE
Kartoza Epic 1: User Story 2: Update existing record

### ISSUE THREAD

**Issue by AlwynSmit** [healthsites/healthsites#994]
# Expectation
As an HS.io logged in user, when I update an existing record in the user interface, I want to see the updates to that record appear in osm.org after a short interval.

# Acceptance criteria
Given that the HS.io UI is verified through unit testing to meet the specified requirements, when a user updates an existing record in HS.IO then these changes shall appear in OSM associated with the same way or node id as the pre-updated record and be retrievable via overpass.

child of #992

**Comment by meomancer** [comment]
Fixed by : https://github.com/healthsites/healthsites/issues/1099
