### ISSUE TITLE
Kartoza Epic 2: User Story 1: Access HS.io via a public API

### ISSUE THREAD

**Issue by AlwynSmit** [healthsites/healthsites#997]
# Expectation
As a system integrator I want to be able to access HS.io via a public API that recently added HS records can be harvested and published to third party platforms.

# Acceptance criteria
Given that the API are verified through unit testing to meet the specified requirements, when the API is used then Aether server will be able to harvest recently added records from HS.io

child of #996

**Comment by timlinux** [comment]
To start we would publish data added in the last 24 hours

**Comment by timlinux** [comment]
1 day of work estimated

**Comment by timlinux** [comment]
See #1018 for digest details

**Comment by meomancer** [comment]
Some of API already done
Workable ticket : https://github.com/healthsites/healthsites/issues/1116

**Comment by meomancer** [comment]
Additional ticket : https://github.com/healthsites/healthsites/issues/1257
